// Code generated by Fern. DO NOT EDIT.

package roamhq

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersCreateAssetRequest(t *testing.T) {
	t.Run("SetName", func(t *testing.T) {
		obj := &CreateAssetRequest{}
		var fernTestValueName string
		obj.SetName(fernTestValueName)
		assert.Equal(t, fernTestValueName, obj.Name)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSize", func(t *testing.T) {
		obj := &CreateAssetRequest{}
		var fernTestValueSize *int
		obj.SetSize(fernTestValueSize)
		assert.Equal(t, fernTestValueSize, obj.Size)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPurpose", func(t *testing.T) {
		obj := &CreateAssetRequest{}
		var fernTestValuePurpose *CreateAssetRequestPurpose
		obj.SetPurpose(fernTestValuePurpose)
		assert.Equal(t, fernTestValuePurpose, obj.Purpose)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitCreateAssetRequest(t *testing.T) {
	t.Run("SetName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateAssetRequest{}
		var fernTestValueName string

		// Act
		obj.SetName(fernTestValueName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSize_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateAssetRequest{}
		var fernTestValueSize *int

		// Act
		obj.SetSize(fernTestValueSize)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPurpose_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateAssetRequest{}
		var fernTestValuePurpose *CreateAssetRequestPurpose

		// Act
		obj.SetPurpose(fernTestValuePurpose)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersCreateAssetResponse(t *testing.T) {
	t.Run("SetAssetID", func(t *testing.T) {
		obj := &CreateAssetResponse{}
		var fernTestValueAssetID string
		obj.SetAssetID(fernTestValueAssetID)
		assert.Equal(t, fernTestValueAssetID, obj.AssetID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetUploadURL", func(t *testing.T) {
		obj := &CreateAssetResponse{}
		var fernTestValueUploadURL string
		obj.SetUploadURL(fernTestValueUploadURL)
		assert.Equal(t, fernTestValueUploadURL, obj.UploadURL)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetUploadMethod", func(t *testing.T) {
		obj := &CreateAssetResponse{}
		var fernTestValueUploadMethod string
		obj.SetUploadMethod(fernTestValueUploadMethod)
		assert.Equal(t, fernTestValueUploadMethod, obj.UploadMethod)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetUploadHeaders", func(t *testing.T) {
		obj := &CreateAssetResponse{}
		var fernTestValueUploadHeaders map[string]string
		obj.SetUploadHeaders(fernTestValueUploadHeaders)
		assert.Equal(t, fernTestValueUploadHeaders, obj.UploadHeaders)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetImageURL", func(t *testing.T) {
		obj := &CreateAssetResponse{}
		var fernTestValueImageURL *string
		obj.SetImageURL(fernTestValueImageURL)
		assert.Equal(t, fernTestValueImageURL, obj.ImageURL)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersCreateAssetResponse(t *testing.T) {
	t.Run("GetAssetID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateAssetResponse{}
		var expected string
		obj.AssetID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetAssetID(), "getter should return the property value")
	})

	t.Run("GetAssetID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CreateAssetResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetAssetID() // Should return zero value
	})

	t.Run("GetUploadURL", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateAssetResponse{}
		var expected string
		obj.UploadURL = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetUploadURL(), "getter should return the property value")
	})

	t.Run("GetUploadURL_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CreateAssetResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetUploadURL() // Should return zero value
	})

	t.Run("GetUploadMethod", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateAssetResponse{}
		var expected string
		obj.UploadMethod = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetUploadMethod(), "getter should return the property value")
	})

	t.Run("GetUploadMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CreateAssetResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetUploadMethod() // Should return zero value
	})

	t.Run("GetUploadHeaders", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateAssetResponse{}
		var expected map[string]string
		obj.UploadHeaders = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetUploadHeaders(), "getter should return the property value")
	})

	t.Run("GetUploadHeaders_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateAssetResponse{}
		obj.UploadHeaders = nil

		// Act & Assert
		assert.Nil(t, obj.GetUploadHeaders(), "getter should return nil when property is nil")
	})

	t.Run("GetUploadHeaders_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CreateAssetResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetUploadHeaders() // Should return zero value
	})

	t.Run("GetImageURL", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateAssetResponse{}
		var expected *string
		obj.ImageURL = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetImageURL(), "getter should return the property value")
	})

	t.Run("GetImageURL_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateAssetResponse{}
		obj.ImageURL = nil

		// Act & Assert
		assert.Nil(t, obj.GetImageURL(), "getter should return nil when property is nil")
	})

	t.Run("GetImageURL_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CreateAssetResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetImageURL() // Should return zero value
	})

}

func TestSettersMarkExplicitCreateAssetResponse(t *testing.T) {
	t.Run("SetAssetID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateAssetResponse{}
		var fernTestValueAssetID string

		// Act
		obj.SetAssetID(fernTestValueAssetID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetUploadURL_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateAssetResponse{}
		var fernTestValueUploadURL string

		// Act
		obj.SetUploadURL(fernTestValueUploadURL)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetUploadMethod_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateAssetResponse{}
		var fernTestValueUploadMethod string

		// Act
		obj.SetUploadMethod(fernTestValueUploadMethod)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetUploadHeaders_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateAssetResponse{}
		var fernTestValueUploadHeaders map[string]string

		// Act
		obj.SetUploadHeaders(fernTestValueUploadHeaders)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetImageURL_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateAssetResponse{}
		var fernTestValueImageURL *string

		// Act
		obj.SetImageURL(fernTestValueImageURL)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingCreateAssetResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateAssetResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled CreateAssetResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj CreateAssetResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj CreateAssetResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringCreateAssetResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &CreateAssetResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CreateAssetResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestEnumCreateAssetRequestPurpose(t *testing.T) {
	t.Run("NewFromString_file", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreateAssetRequestPurposeFromString("file")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreateAssetRequestPurpose("file"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_story", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreateAssetRequestPurposeFromString("story")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreateAssetRequestPurpose("story"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_avatar", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreateAssetRequestPurposeFromString("avatar")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreateAssetRequestPurpose("avatar"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewCreateAssetRequestPurposeFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewCreateAssetRequestPurposeFromString("file")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestExtraPropertiesCreateAssetResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &CreateAssetResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CreateAssetResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
