// Code generated by Fern. DO NOT EDIT.

package roamhq

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
	time "time"
)

func TestSettersListConversationRequest(t *testing.T) {
	t.Run("SetBefore", func(t *testing.T) {
		obj := &ListConversationRequest{}
		var fernTestValueBefore *time.Time
		obj.SetBefore(fernTestValueBefore)
		assert.Equal(t, fernTestValueBefore, obj.Before)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetAfter", func(t *testing.T) {
		obj := &ListConversationRequest{}
		var fernTestValueAfter *time.Time
		obj.SetAfter(fernTestValueAfter)
		assert.Equal(t, fernTestValueAfter, obj.After)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetAscending", func(t *testing.T) {
		obj := &ListConversationRequest{}
		var fernTestValueAscending *bool
		obj.SetAscending(fernTestValueAscending)
		assert.Equal(t, fernTestValueAscending, obj.Ascending)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLimit", func(t *testing.T) {
		obj := &ListConversationRequest{}
		var fernTestValueLimit *int
		obj.SetLimit(fernTestValueLimit)
		assert.Equal(t, fernTestValueLimit, obj.Limit)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCursor", func(t *testing.T) {
		obj := &ListConversationRequest{}
		var fernTestValueCursor *string
		obj.SetCursor(fernTestValueCursor)
		assert.Equal(t, fernTestValueCursor, obj.Cursor)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitListConversationRequest(t *testing.T) {
	t.Run("SetBefore_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListConversationRequest{}
		var fernTestValueBefore *time.Time

		// Act
		obj.SetBefore(fernTestValueBefore)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetAfter_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListConversationRequest{}
		var fernTestValueAfter *time.Time

		// Act
		obj.SetAfter(fernTestValueAfter)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetAscending_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListConversationRequest{}
		var fernTestValueAscending *bool

		// Act
		obj.SetAscending(fernTestValueAscending)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLimit_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListConversationRequest{}
		var fernTestValueLimit *int

		// Act
		obj.SetLimit(fernTestValueLimit)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCursor_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListConversationRequest{}
		var fernTestValueCursor *string

		// Act
		obj.SetCursor(fernTestValueCursor)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersListConversationResponse(t *testing.T) {
	t.Run("SetConversations", func(t *testing.T) {
		obj := &ListConversationResponse{}
		var fernTestValueConversations []*ListConversationResponseConversationsItem
		obj.SetConversations(fernTestValueConversations)
		assert.Equal(t, fernTestValueConversations, obj.Conversations)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetNextCursor", func(t *testing.T) {
		obj := &ListConversationResponse{}
		var fernTestValueNextCursor *string
		obj.SetNextCursor(fernTestValueNextCursor)
		assert.Equal(t, fernTestValueNextCursor, obj.NextCursor)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersListConversationResponse(t *testing.T) {
	t.Run("GetConversations", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListConversationResponse{}
		var expected []*ListConversationResponseConversationsItem
		obj.Conversations = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetConversations(), "getter should return the property value")
	})

	t.Run("GetConversations_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListConversationResponse{}
		obj.Conversations = nil

		// Act & Assert
		assert.Nil(t, obj.GetConversations(), "getter should return nil when property is nil")
	})

	t.Run("GetConversations_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListConversationResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetConversations() // Should return zero value
	})

	t.Run("GetNextCursor", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListConversationResponse{}
		var expected *string
		obj.NextCursor = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetNextCursor(), "getter should return the property value")
	})

	t.Run("GetNextCursor_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListConversationResponse{}
		obj.NextCursor = nil

		// Act & Assert
		assert.Nil(t, obj.GetNextCursor(), "getter should return nil when property is nil")
	})

	t.Run("GetNextCursor_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListConversationResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetNextCursor() // Should return zero value
	})

}

func TestSettersMarkExplicitListConversationResponse(t *testing.T) {
	t.Run("SetConversations_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListConversationResponse{}
		var fernTestValueConversations []*ListConversationResponseConversationsItem

		// Act
		obj.SetConversations(fernTestValueConversations)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetNextCursor_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListConversationResponse{}
		var fernTestValueNextCursor *string

		// Act
		obj.SetNextCursor(fernTestValueNextCursor)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersListConversationResponseConversationsItem(t *testing.T) {
	t.Run("SetID", func(t *testing.T) {
		obj := &ListConversationResponseConversationsItem{}
		var fernTestValueID *string
		obj.SetID(fernTestValueID)
		assert.Equal(t, fernTestValueID, obj.ID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPlace", func(t *testing.T) {
		obj := &ListConversationResponseConversationsItem{}
		var fernTestValuePlace *string
		obj.SetPlace(fernTestValuePlace)
		assert.Equal(t, fernTestValuePlace, obj.Place)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetRoom", func(t *testing.T) {
		obj := &ListConversationResponseConversationsItem{}
		var fernTestValueRoom *string
		obj.SetRoom(fernTestValueRoom)
		assert.Equal(t, fernTestValueRoom, obj.Room)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetRoomType", func(t *testing.T) {
		obj := &ListConversationResponseConversationsItem{}
		var fernTestValueRoomType *string
		obj.SetRoomType(fernTestValueRoomType)
		assert.Equal(t, fernTestValueRoomType, obj.RoomType)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetStart", func(t *testing.T) {
		obj := &ListConversationResponseConversationsItem{}
		var fernTestValueStart *time.Time
		obj.SetStart(fernTestValueStart)
		assert.Equal(t, fernTestValueStart, obj.Start)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetEnd", func(t *testing.T) {
		obj := &ListConversationResponseConversationsItem{}
		var fernTestValueEnd *time.Time
		obj.SetEnd(fernTestValueEnd)
		assert.Equal(t, fernTestValueEnd, obj.End)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetParticipants", func(t *testing.T) {
		obj := &ListConversationResponseConversationsItem{}
		var fernTestValueParticipants []*ListConversationResponseConversationsItemParticipantsItem
		obj.SetParticipants(fernTestValueParticipants)
		assert.Equal(t, fernTestValueParticipants, obj.Participants)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMeetingLinkIDs", func(t *testing.T) {
		obj := &ListConversationResponseConversationsItem{}
		var fernTestValueMeetingLinkIDs []string
		obj.SetMeetingLinkIDs(fernTestValueMeetingLinkIDs)
		assert.Equal(t, fernTestValueMeetingLinkIDs, obj.MeetingLinkIDs)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersListConversationResponseConversationsItem(t *testing.T) {
	t.Run("GetID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListConversationResponseConversationsItem{}
		var expected *string
		obj.ID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetID(), "getter should return the property value")
	})

	t.Run("GetID_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListConversationResponseConversationsItem{}
		obj.ID = nil

		// Act & Assert
		assert.Nil(t, obj.GetID(), "getter should return nil when property is nil")
	})

	t.Run("GetID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListConversationResponseConversationsItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetID() // Should return zero value
	})

	t.Run("GetPlace", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListConversationResponseConversationsItem{}
		var expected *string
		obj.Place = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetPlace(), "getter should return the property value")
	})

	t.Run("GetPlace_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListConversationResponseConversationsItem{}
		obj.Place = nil

		// Act & Assert
		assert.Nil(t, obj.GetPlace(), "getter should return nil when property is nil")
	})

	t.Run("GetPlace_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListConversationResponseConversationsItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetPlace() // Should return zero value
	})

	t.Run("GetRoom", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListConversationResponseConversationsItem{}
		var expected *string
		obj.Room = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetRoom(), "getter should return the property value")
	})

	t.Run("GetRoom_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListConversationResponseConversationsItem{}
		obj.Room = nil

		// Act & Assert
		assert.Nil(t, obj.GetRoom(), "getter should return nil when property is nil")
	})

	t.Run("GetRoom_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListConversationResponseConversationsItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetRoom() // Should return zero value
	})

	t.Run("GetRoomType", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListConversationResponseConversationsItem{}
		var expected *string
		obj.RoomType = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetRoomType(), "getter should return the property value")
	})

	t.Run("GetRoomType_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListConversationResponseConversationsItem{}
		obj.RoomType = nil

		// Act & Assert
		assert.Nil(t, obj.GetRoomType(), "getter should return nil when property is nil")
	})

	t.Run("GetRoomType_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListConversationResponseConversationsItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetRoomType() // Should return zero value
	})

	t.Run("GetStart", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListConversationResponseConversationsItem{}
		var expected *time.Time
		obj.Start = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetStart(), "getter should return the property value")
	})

	t.Run("GetStart_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListConversationResponseConversationsItem{}
		obj.Start = nil

		// Act & Assert
		assert.Nil(t, obj.GetStart(), "getter should return nil when property is nil")
	})

	t.Run("GetStart_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListConversationResponseConversationsItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetStart() // Should return zero value
	})

	t.Run("GetEnd", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListConversationResponseConversationsItem{}
		var expected *time.Time
		obj.End = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetEnd(), "getter should return the property value")
	})

	t.Run("GetEnd_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListConversationResponseConversationsItem{}
		obj.End = nil

		// Act & Assert
		assert.Nil(t, obj.GetEnd(), "getter should return nil when property is nil")
	})

	t.Run("GetEnd_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListConversationResponseConversationsItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetEnd() // Should return zero value
	})

	t.Run("GetParticipants", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListConversationResponseConversationsItem{}
		var expected []*ListConversationResponseConversationsItemParticipantsItem
		obj.Participants = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetParticipants(), "getter should return the property value")
	})

	t.Run("GetParticipants_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListConversationResponseConversationsItem{}
		obj.Participants = nil

		// Act & Assert
		assert.Nil(t, obj.GetParticipants(), "getter should return nil when property is nil")
	})

	t.Run("GetParticipants_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListConversationResponseConversationsItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetParticipants() // Should return zero value
	})

	t.Run("GetMeetingLinkIDs", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListConversationResponseConversationsItem{}
		var expected []string
		obj.MeetingLinkIDs = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetMeetingLinkIDs(), "getter should return the property value")
	})

	t.Run("GetMeetingLinkIDs_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListConversationResponseConversationsItem{}
		obj.MeetingLinkIDs = nil

		// Act & Assert
		assert.Nil(t, obj.GetMeetingLinkIDs(), "getter should return nil when property is nil")
	})

	t.Run("GetMeetingLinkIDs_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListConversationResponseConversationsItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetMeetingLinkIDs() // Should return zero value
	})

}

func TestSettersMarkExplicitListConversationResponseConversationsItem(t *testing.T) {
	t.Run("SetID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListConversationResponseConversationsItem{}
		var fernTestValueID *string

		// Act
		obj.SetID(fernTestValueID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPlace_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListConversationResponseConversationsItem{}
		var fernTestValuePlace *string

		// Act
		obj.SetPlace(fernTestValuePlace)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetRoom_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListConversationResponseConversationsItem{}
		var fernTestValueRoom *string

		// Act
		obj.SetRoom(fernTestValueRoom)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetRoomType_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListConversationResponseConversationsItem{}
		var fernTestValueRoomType *string

		// Act
		obj.SetRoomType(fernTestValueRoomType)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetStart_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListConversationResponseConversationsItem{}
		var fernTestValueStart *time.Time

		// Act
		obj.SetStart(fernTestValueStart)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetEnd_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListConversationResponseConversationsItem{}
		var fernTestValueEnd *time.Time

		// Act
		obj.SetEnd(fernTestValueEnd)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetParticipants_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListConversationResponseConversationsItem{}
		var fernTestValueParticipants []*ListConversationResponseConversationsItemParticipantsItem

		// Act
		obj.SetParticipants(fernTestValueParticipants)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMeetingLinkIDs_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListConversationResponseConversationsItem{}
		var fernTestValueMeetingLinkIDs []string

		// Act
		obj.SetMeetingLinkIDs(fernTestValueMeetingLinkIDs)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersListConversationResponseConversationsItemParticipantsItem(t *testing.T) {
	t.Run("SetName", func(t *testing.T) {
		obj := &ListConversationResponseConversationsItemParticipantsItem{}
		var fernTestValueName *string
		obj.SetName(fernTestValueName)
		assert.Equal(t, fernTestValueName, obj.Name)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetEmail", func(t *testing.T) {
		obj := &ListConversationResponseConversationsItemParticipantsItem{}
		var fernTestValueEmail *string
		obj.SetEmail(fernTestValueEmail)
		assert.Equal(t, fernTestValueEmail, obj.Email)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSeconds", func(t *testing.T) {
		obj := &ListConversationResponseConversationsItemParticipantsItem{}
		var fernTestValueSeconds *float64
		obj.SetSeconds(fernTestValueSeconds)
		assert.Equal(t, fernTestValueSeconds, obj.Seconds)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersListConversationResponseConversationsItemParticipantsItem(t *testing.T) {
	t.Run("GetName", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListConversationResponseConversationsItemParticipantsItem{}
		var expected *string
		obj.Name = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetName(), "getter should return the property value")
	})

	t.Run("GetName_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListConversationResponseConversationsItemParticipantsItem{}
		obj.Name = nil

		// Act & Assert
		assert.Nil(t, obj.GetName(), "getter should return nil when property is nil")
	})

	t.Run("GetName_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListConversationResponseConversationsItemParticipantsItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetName() // Should return zero value
	})

	t.Run("GetEmail", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListConversationResponseConversationsItemParticipantsItem{}
		var expected *string
		obj.Email = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetEmail(), "getter should return the property value")
	})

	t.Run("GetEmail_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListConversationResponseConversationsItemParticipantsItem{}
		obj.Email = nil

		// Act & Assert
		assert.Nil(t, obj.GetEmail(), "getter should return nil when property is nil")
	})

	t.Run("GetEmail_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListConversationResponseConversationsItemParticipantsItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetEmail() // Should return zero value
	})

	t.Run("GetSeconds", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListConversationResponseConversationsItemParticipantsItem{}
		var expected *float64
		obj.Seconds = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSeconds(), "getter should return the property value")
	})

	t.Run("GetSeconds_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListConversationResponseConversationsItemParticipantsItem{}
		obj.Seconds = nil

		// Act & Assert
		assert.Nil(t, obj.GetSeconds(), "getter should return nil when property is nil")
	})

	t.Run("GetSeconds_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListConversationResponseConversationsItemParticipantsItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSeconds() // Should return zero value
	})

}

func TestSettersMarkExplicitListConversationResponseConversationsItemParticipantsItem(t *testing.T) {
	t.Run("SetName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListConversationResponseConversationsItemParticipantsItem{}
		var fernTestValueName *string

		// Act
		obj.SetName(fernTestValueName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetEmail_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListConversationResponseConversationsItemParticipantsItem{}
		var fernTestValueEmail *string

		// Act
		obj.SetEmail(fernTestValueEmail)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSeconds_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListConversationResponseConversationsItemParticipantsItem{}
		var fernTestValueSeconds *float64

		// Act
		obj.SetSeconds(fernTestValueSeconds)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingListConversationResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListConversationResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled ListConversationResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj ListConversationResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj ListConversationResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingListConversationResponseConversationsItem(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListConversationResponseConversationsItem{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled ListConversationResponseConversationsItem
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj ListConversationResponseConversationsItem
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj ListConversationResponseConversationsItem
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingListConversationResponseConversationsItemParticipantsItem(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListConversationResponseConversationsItemParticipantsItem{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled ListConversationResponseConversationsItemParticipantsItem
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj ListConversationResponseConversationsItemParticipantsItem
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj ListConversationResponseConversationsItemParticipantsItem
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringListConversationResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &ListConversationResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListConversationResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringListConversationResponseConversationsItem(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &ListConversationResponseConversationsItem{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListConversationResponseConversationsItem
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringListConversationResponseConversationsItemParticipantsItem(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &ListConversationResponseConversationsItemParticipantsItem{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListConversationResponseConversationsItemParticipantsItem
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestExtraPropertiesListConversationResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &ListConversationResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListConversationResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesListConversationResponseConversationsItem(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &ListConversationResponseConversationsItem{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListConversationResponseConversationsItem
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesListConversationResponseConversationsItemParticipantsItem(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &ListConversationResponseConversationsItemParticipantsItem{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListConversationResponseConversationsItemParticipantsItem
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
