// Code generated by Fern. DO NOT EDIT.

package roamhq

import (
	json "encoding/json"
	fmt "fmt"
	big "math/big"
	internal "ro.am/roamhq/internal"
	time "time"
)

var (
	listConversationRequestFieldBefore    = big.NewInt(1 << 0)
	listConversationRequestFieldAfter     = big.NewInt(1 << 1)
	listConversationRequestFieldAscending = big.NewInt(1 << 2)
	listConversationRequestFieldLimit     = big.NewInt(1 << 3)
	listConversationRequestFieldCursor    = big.NewInt(1 << 4)
)

type ListConversationRequest struct {
	// Only return conversations that started before this ISO-8601 timestamp.
	Before *time.Time `json:"-" url:"before,omitempty"`
	// Only return conversations that started after this ISO-8601 timestamp.
	After *time.Time `json:"-" url:"after,omitempty"`
	// Sort results in ascending order by start time. Default is descending (newest first).
	Ascending *bool `json:"-" url:"ascending,omitempty"`
	// The number of conversations to return per response.
	Limit *int `json:"-" url:"limit,omitempty"`
	// Opaque pagination cursor from a previous response's `nextCursor`. Do not construct cursors manually.
	Cursor *string `json:"-" url:"cursor,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListConversationRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetBefore sets the Before field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListConversationRequest) SetBefore(before *time.Time) {
	l.Before = before
	l.require(listConversationRequestFieldBefore)
}

// SetAfter sets the After field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListConversationRequest) SetAfter(after *time.Time) {
	l.After = after
	l.require(listConversationRequestFieldAfter)
}

// SetAscending sets the Ascending field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListConversationRequest) SetAscending(ascending *bool) {
	l.Ascending = ascending
	l.require(listConversationRequestFieldAscending)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListConversationRequest) SetLimit(limit *int) {
	l.Limit = limit
	l.require(listConversationRequestFieldLimit)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListConversationRequest) SetCursor(cursor *string) {
	l.Cursor = cursor
	l.require(listConversationRequestFieldCursor)
}

var (
	listConversationResponseFieldConversations = big.NewInt(1 << 0)
	listConversationResponseFieldNextCursor    = big.NewInt(1 << 1)
)

type ListConversationResponse struct {
	Conversations []*ListConversationResponseConversationsItem `json:"conversations,omitempty" url:"conversations,omitempty"`
	// Pagination cursor for fetching the next page of results
	NextCursor *string `json:"nextCursor,omitempty" url:"nextCursor,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListConversationResponse) GetConversations() []*ListConversationResponseConversationsItem {
	if l == nil {
		return nil
	}
	return l.Conversations
}

func (l *ListConversationResponse) GetNextCursor() *string {
	if l == nil {
		return nil
	}
	return l.NextCursor
}

func (l *ListConversationResponse) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListConversationResponse) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetConversations sets the Conversations field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListConversationResponse) SetConversations(conversations []*ListConversationResponseConversationsItem) {
	l.Conversations = conversations
	l.require(listConversationResponseFieldConversations)
}

// SetNextCursor sets the NextCursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListConversationResponse) SetNextCursor(nextCursor *string) {
	l.NextCursor = nextCursor
	l.require(listConversationResponseFieldNextCursor)
}

func (l *ListConversationResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ListConversationResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListConversationResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListConversationResponse) MarshalJSON() ([]byte, error) {
	type embed ListConversationResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListConversationResponse) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

var (
	listConversationResponseConversationsItemFieldID             = big.NewInt(1 << 0)
	listConversationResponseConversationsItemFieldPlace          = big.NewInt(1 << 1)
	listConversationResponseConversationsItemFieldRoom           = big.NewInt(1 << 2)
	listConversationResponseConversationsItemFieldRoomType       = big.NewInt(1 << 3)
	listConversationResponseConversationsItemFieldStart          = big.NewInt(1 << 4)
	listConversationResponseConversationsItemFieldEnd            = big.NewInt(1 << 5)
	listConversationResponseConversationsItemFieldParticipants   = big.NewInt(1 << 6)
	listConversationResponseConversationsItemFieldMeetingLinkIDs = big.NewInt(1 << 7)
)

type ListConversationResponseConversationsItem struct {
	// Unique identifier for the conversation (meeting GUID)
	ID *string `json:"id,omitempty" url:"id,omitempty"`
	// The place where the conversation occurred
	Place *string `json:"place,omitempty" url:"place,omitempty"`
	// The room name
	Room *string `json:"room,omitempty" url:"room,omitempty"`
	// The type of room
	RoomType *string `json:"roomType,omitempty" url:"roomType,omitempty"`
	// When the conversation started (ISO-8601)
	Start *time.Time `json:"start,omitempty" url:"start,omitempty"`
	// When the conversation ended (ISO-8601)
	End *time.Time `json:"end,omitempty" url:"end,omitempty"`
	// List of participants (requires `user:read` scope)
	Participants []*ListConversationResponseConversationsItemParticipantsItem `json:"participants,omitempty" url:"participants,omitempty"`
	// IDs of meeting links associated with this conversation
	MeetingLinkIDs []string `json:"meetingLinkIds,omitempty" url:"meetingLinkIds,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListConversationResponseConversationsItem) GetID() *string {
	if l == nil {
		return nil
	}
	return l.ID
}

func (l *ListConversationResponseConversationsItem) GetPlace() *string {
	if l == nil {
		return nil
	}
	return l.Place
}

func (l *ListConversationResponseConversationsItem) GetRoom() *string {
	if l == nil {
		return nil
	}
	return l.Room
}

func (l *ListConversationResponseConversationsItem) GetRoomType() *string {
	if l == nil {
		return nil
	}
	return l.RoomType
}

func (l *ListConversationResponseConversationsItem) GetStart() *time.Time {
	if l == nil {
		return nil
	}
	return l.Start
}

func (l *ListConversationResponseConversationsItem) GetEnd() *time.Time {
	if l == nil {
		return nil
	}
	return l.End
}

func (l *ListConversationResponseConversationsItem) GetParticipants() []*ListConversationResponseConversationsItemParticipantsItem {
	if l == nil {
		return nil
	}
	return l.Participants
}

func (l *ListConversationResponseConversationsItem) GetMeetingLinkIDs() []string {
	if l == nil {
		return nil
	}
	return l.MeetingLinkIDs
}

func (l *ListConversationResponseConversationsItem) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListConversationResponseConversationsItem) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListConversationResponseConversationsItem) SetID(id *string) {
	l.ID = id
	l.require(listConversationResponseConversationsItemFieldID)
}

// SetPlace sets the Place field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListConversationResponseConversationsItem) SetPlace(place *string) {
	l.Place = place
	l.require(listConversationResponseConversationsItemFieldPlace)
}

// SetRoom sets the Room field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListConversationResponseConversationsItem) SetRoom(room *string) {
	l.Room = room
	l.require(listConversationResponseConversationsItemFieldRoom)
}

// SetRoomType sets the RoomType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListConversationResponseConversationsItem) SetRoomType(roomType *string) {
	l.RoomType = roomType
	l.require(listConversationResponseConversationsItemFieldRoomType)
}

// SetStart sets the Start field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListConversationResponseConversationsItem) SetStart(start *time.Time) {
	l.Start = start
	l.require(listConversationResponseConversationsItemFieldStart)
}

// SetEnd sets the End field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListConversationResponseConversationsItem) SetEnd(end *time.Time) {
	l.End = end
	l.require(listConversationResponseConversationsItemFieldEnd)
}

// SetParticipants sets the Participants field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListConversationResponseConversationsItem) SetParticipants(participants []*ListConversationResponseConversationsItemParticipantsItem) {
	l.Participants = participants
	l.require(listConversationResponseConversationsItemFieldParticipants)
}

// SetMeetingLinkIDs sets the MeetingLinkIDs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListConversationResponseConversationsItem) SetMeetingLinkIDs(meetingLinkIDs []string) {
	l.MeetingLinkIDs = meetingLinkIDs
	l.require(listConversationResponseConversationsItemFieldMeetingLinkIDs)
}

func (l *ListConversationResponseConversationsItem) UnmarshalJSON(data []byte) error {
	type embed ListConversationResponseConversationsItem
	var unmarshaler = struct {
		embed
		Start *internal.DateTime `json:"start,omitempty"`
		End   *internal.DateTime `json:"end,omitempty"`
	}{
		embed: embed(*l),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*l = ListConversationResponseConversationsItem(unmarshaler.embed)
	l.Start = unmarshaler.Start.TimePtr()
	l.End = unmarshaler.End.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListConversationResponseConversationsItem) MarshalJSON() ([]byte, error) {
	type embed ListConversationResponseConversationsItem
	var marshaler = struct {
		embed
		Start *internal.DateTime `json:"start,omitempty"`
		End   *internal.DateTime `json:"end,omitempty"`
	}{
		embed: embed(*l),
		Start: internal.NewOptionalDateTime(l.Start),
		End:   internal.NewOptionalDateTime(l.End),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListConversationResponseConversationsItem) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

var (
	listConversationResponseConversationsItemParticipantsItemFieldName    = big.NewInt(1 << 0)
	listConversationResponseConversationsItemParticipantsItemFieldEmail   = big.NewInt(1 << 1)
	listConversationResponseConversationsItemParticipantsItemFieldSeconds = big.NewInt(1 << 2)
)

type ListConversationResponseConversationsItemParticipantsItem struct {
	// Display name of the participant
	Name *string `json:"name,omitempty" url:"name,omitempty"`
	// Email address (requires `user:read.email` scope)
	Email *string `json:"email,omitempty" url:"email,omitempty"`
	// Duration the participant was in the conversation, in seconds
	Seconds *float64 `json:"seconds,omitempty" url:"seconds,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListConversationResponseConversationsItemParticipantsItem) GetName() *string {
	if l == nil {
		return nil
	}
	return l.Name
}

func (l *ListConversationResponseConversationsItemParticipantsItem) GetEmail() *string {
	if l == nil {
		return nil
	}
	return l.Email
}

func (l *ListConversationResponseConversationsItemParticipantsItem) GetSeconds() *float64 {
	if l == nil {
		return nil
	}
	return l.Seconds
}

func (l *ListConversationResponseConversationsItemParticipantsItem) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListConversationResponseConversationsItemParticipantsItem) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListConversationResponseConversationsItemParticipantsItem) SetName(name *string) {
	l.Name = name
	l.require(listConversationResponseConversationsItemParticipantsItemFieldName)
}

// SetEmail sets the Email field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListConversationResponseConversationsItemParticipantsItem) SetEmail(email *string) {
	l.Email = email
	l.require(listConversationResponseConversationsItemParticipantsItemFieldEmail)
}

// SetSeconds sets the Seconds field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListConversationResponseConversationsItemParticipantsItem) SetSeconds(seconds *float64) {
	l.Seconds = seconds
	l.require(listConversationResponseConversationsItemParticipantsItemFieldSeconds)
}

func (l *ListConversationResponseConversationsItemParticipantsItem) UnmarshalJSON(data []byte) error {
	type unmarshaler ListConversationResponseConversationsItemParticipantsItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListConversationResponseConversationsItemParticipantsItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListConversationResponseConversationsItemParticipantsItem) MarshalJSON() ([]byte, error) {
	type embed ListConversationResponseConversationsItemParticipantsItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListConversationResponseConversationsItemParticipantsItem) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}
