// Code generated by Fern. DO NOT EDIT.

package roamhq

import (
	json "encoding/json"
	fmt "fmt"
	big "math/big"
	internal "ro.am/roamhq/internal"
	time "time"
)

var (
	addGroupRequestFieldID      = big.NewInt(1 << 0)
	addGroupRequestFieldMembers = big.NewInt(1 << 1)
)

type AddGroupRequest struct {
	// Group ID
	ID string `json:"id" url:"-"`
	// List of members to add with their roles
	Members []*AddGroupRequestMembersItem `json:"members,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (a *AddGroupRequest) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddGroupRequest) SetID(id string) {
	a.ID = id
	a.require(addGroupRequestFieldID)
}

// SetMembers sets the Members field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddGroupRequest) SetMembers(members []*AddGroupRequestMembersItem) {
	a.Members = members
	a.require(addGroupRequestFieldMembers)
}

func (a *AddGroupRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler AddGroupRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*a = AddGroupRequest(body)
	return nil
}

func (a *AddGroupRequest) MarshalJSON() ([]byte, error) {
	type embed AddGroupRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	archiveGroupRequestFieldID = big.NewInt(1 << 0)
)

type ArchiveGroupRequest struct {
	// The group ID to archive.
	ID string `json:"id" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (a *ArchiveGroupRequest) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *ArchiveGroupRequest) SetID(id string) {
	a.ID = id
	a.require(archiveGroupRequestFieldID)
}

func (a *ArchiveGroupRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler ArchiveGroupRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*a = ArchiveGroupRequest(body)
	return nil
}

func (a *ArchiveGroupRequest) MarshalJSON() ([]byte, error) {
	type embed ArchiveGroupRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	createGroupRequestFieldName           = big.NewInt(1 << 0)
	createGroupRequestFieldDescription    = big.NewInt(1 << 1)
	createGroupRequestFieldPrivate        = big.NewInt(1 << 2)
	createGroupRequestFieldEnforceThreads = big.NewInt(1 << 3)
	createGroupRequestFieldMembers        = big.NewInt(1 << 4)
)

type CreateGroupRequest struct {
	// Name of the group
	Name string `json:"name" url:"-"`
	// Description of the group
	Description *string `json:"description,omitempty" url:"-"`
	// Whether the group is private (default false)
	Private *bool `json:"private,omitempty" url:"-"`
	// Whether to enforce threaded conversations
	EnforceThreads *bool `json:"enforceThreads,omitempty" url:"-"`
	// Group members with their roles
	Members []*CreateGroupRequestMembersItem `json:"members" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateGroupRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateGroupRequest) SetName(name string) {
	c.Name = name
	c.require(createGroupRequestFieldName)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateGroupRequest) SetDescription(description *string) {
	c.Description = description
	c.require(createGroupRequestFieldDescription)
}

// SetPrivate sets the Private field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateGroupRequest) SetPrivate(private *bool) {
	c.Private = private
	c.require(createGroupRequestFieldPrivate)
}

// SetEnforceThreads sets the EnforceThreads field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateGroupRequest) SetEnforceThreads(enforceThreads *bool) {
	c.EnforceThreads = enforceThreads
	c.require(createGroupRequestFieldEnforceThreads)
}

// SetMembers sets the Members field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateGroupRequest) SetMembers(members []*CreateGroupRequestMembersItem) {
	c.Members = members
	c.require(createGroupRequestFieldMembers)
}

func (c *CreateGroupRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateGroupRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateGroupRequest(body)
	return nil
}

func (c *CreateGroupRequest) MarshalJSON() ([]byte, error) {
	type embed CreateGroupRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	infoGroupRequestFieldID   = big.NewInt(1 << 0)
	infoGroupRequestFieldName = big.NewInt(1 << 1)
)

type InfoGroupRequest struct {
	// The group's ID. Mutually exclusive with `name`.
	ID *string `json:"-" url:"id,omitempty"`
	// The group's name. Mutually exclusive with `id`. Returns first match if multiple groups have the same name.
	Name *string `json:"-" url:"name,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (i *InfoGroupRequest) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InfoGroupRequest) SetID(id *string) {
	i.ID = id
	i.require(infoGroupRequestFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InfoGroupRequest) SetName(name *string) {
	i.Name = name
	i.require(infoGroupRequestFieldName)
}

var (
	joinGroupRequestFieldID = big.NewInt(1 << 0)
)

type JoinGroupRequest struct {
	// Group ID
	ID string `json:"id" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (j *JoinGroupRequest) require(field *big.Int) {
	if j.explicitFields == nil {
		j.explicitFields = big.NewInt(0)
	}
	j.explicitFields.Or(j.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (j *JoinGroupRequest) SetID(id string) {
	j.ID = id
	j.require(joinGroupRequestFieldID)
}

func (j *JoinGroupRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler JoinGroupRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*j = JoinGroupRequest(body)
	return nil
}

func (j *JoinGroupRequest) MarshalJSON() ([]byte, error) {
	type embed JoinGroupRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*j),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, j.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	listGroupRequestFieldQuery  = big.NewInt(1 << 0)
	listGroupRequestFieldType   = big.NewInt(1 << 1)
	listGroupRequestFieldLimit  = big.NewInt(1 << 2)
	listGroupRequestFieldCursor = big.NewInt(1 << 3)
)

type ListGroupRequest struct {
	// Text filter. Groups are ranked by how well their name matches the query.
	Query *string `json:"-" url:"query,omitempty"`
	// Comma-separated list of group types to include. Must be one or
	// more of `standard`, `magicast`, `meeting`, `roam`, `onair`.
	// Defaults to all types.
	Type *string `json:"-" url:"type,omitempty"`
	// Number of groups to return per page (default 50, max 100).
	Limit *int `json:"-" url:"limit,omitempty"`
	// Opaque pagination cursor from a previous response's `nextCursor`. Do not construct cursors manually.
	Cursor *string `json:"-" url:"cursor,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListGroupRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetQuery sets the Query field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListGroupRequest) SetQuery(query *string) {
	l.Query = query
	l.require(listGroupRequestFieldQuery)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListGroupRequest) SetType(type_ *string) {
	l.Type = type_
	l.require(listGroupRequestFieldType)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListGroupRequest) SetLimit(limit *int) {
	l.Limit = limit
	l.require(listGroupRequestFieldLimit)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListGroupRequest) SetCursor(cursor *string) {
	l.Cursor = cursor
	l.require(listGroupRequestFieldCursor)
}

var (
	membersGroupRequestFieldID     = big.NewInt(1 << 0)
	membersGroupRequestFieldLimit  = big.NewInt(1 << 1)
	membersGroupRequestFieldCursor = big.NewInt(1 << 2)
)

type MembersGroupRequest struct {
	// Group ID.
	ID string `json:"-" url:"id"`
	// The number of members to return per response. Default is 10.
	Limit *int `json:"-" url:"limit,omitempty"`
	// Opaque pagination cursor from a previous response's `nextCursor`. Do not construct cursors manually.
	Cursor *string `json:"-" url:"cursor,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (m *MembersGroupRequest) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MembersGroupRequest) SetID(id string) {
	m.ID = id
	m.require(membersGroupRequestFieldID)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MembersGroupRequest) SetLimit(limit *int) {
	m.Limit = limit
	m.require(membersGroupRequestFieldLimit)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MembersGroupRequest) SetCursor(cursor *string) {
	m.Cursor = cursor
	m.require(membersGroupRequestFieldCursor)
}

var (
	removeGroupRequestFieldID      = big.NewInt(1 << 0)
	removeGroupRequestFieldMembers = big.NewInt(1 << 1)
)

type RemoveGroupRequest struct {
	// Group ID
	ID string `json:"id" url:"-"`
	// List of member IDs or email addresses to remove
	Members []string `json:"members" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *RemoveGroupRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RemoveGroupRequest) SetID(id string) {
	r.ID = id
	r.require(removeGroupRequestFieldID)
}

// SetMembers sets the Members field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RemoveGroupRequest) SetMembers(members []string) {
	r.Members = members
	r.require(removeGroupRequestFieldMembers)
}

func (r *RemoveGroupRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler RemoveGroupRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*r = RemoveGroupRequest(body)
	return nil
}

func (r *RemoveGroupRequest) MarshalJSON() ([]byte, error) {
	type embed RemoveGroupRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	renameGroupRequestFieldID   = big.NewInt(1 << 0)
	renameGroupRequestFieldName = big.NewInt(1 << 1)
)

type RenameGroupRequest struct {
	// The group ID
	ID string `json:"id" url:"-"`
	// The new name for the group
	Name string `json:"name" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *RenameGroupRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RenameGroupRequest) SetID(id string) {
	r.ID = id
	r.require(renameGroupRequestFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RenameGroupRequest) SetName(name string) {
	r.Name = name
	r.require(renameGroupRequestFieldName)
}

func (r *RenameGroupRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler RenameGroupRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*r = RenameGroupRequest(body)
	return nil
}

func (r *RenameGroupRequest) MarshalJSON() ([]byte, error) {
	type embed RenameGroupRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

// A group (channel) in the Roam workspace
var (
	groupFieldID                  = big.NewInt(1 << 0)
	groupFieldChatID              = big.NewInt(1 << 1)
	groupFieldName                = big.NewInt(1 << 2)
	groupFieldType                = big.NewInt(1 << 3)
	groupFieldAccessMode          = big.NewInt(1 << 4)
	groupFieldGroupManagement     = big.NewInt(1 << 5)
	groupFieldEnforceThreadedMode = big.NewInt(1 << 6)
	groupFieldDateCreated         = big.NewInt(1 << 7)
	groupFieldImageURL            = big.NewInt(1 << 8)
)

type Group struct {
	// The group's unique identifier
	ID string `json:"id" url:"id"`
	// The group's channel chat ID. Populated by `group.create` and
	// `group.info` (the channel chat is created together with the group), and
	// used to post to or read the channel via the chat endpoints.
	ChatID *string `json:"chatId,omitempty" url:"chatId,omitempty"`
	// Name of the group
	Name string `json:"name" url:"name"`
	// The type of group:
	// - `standard` - A regular channel created by users
	// - `magicast` - A Magicast channel
	// - `meeting` - A meeting channel
	// - `roam` - The main Roam channel (one per workspace)
	// - `onair` - An On-Air channel
	// - `community` - A community channel
	Type GroupType `json:"type" url:"type"`
	// Whether the group is public or private
	AccessMode *GroupAccessMode `json:"accessMode,omitempty" url:"accessMode,omitempty"`
	// Who can manage group settings and membership
	GroupManagement *GroupGroupManagement `json:"groupManagement,omitempty" url:"groupManagement,omitempty"`
	// Whether the group enforces threaded conversations
	EnforceThreadedMode *bool `json:"enforceThreadedMode,omitempty" url:"enforceThreadedMode,omitempty"`
	// When the group was created
	DateCreated *time.Time `json:"dateCreated,omitempty" url:"dateCreated,omitempty"`
	// URL of the group's image
	ImageURL *string `json:"imageUrl,omitempty" url:"imageUrl,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *Group) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *Group) GetChatID() *string {
	if g == nil {
		return nil
	}
	return g.ChatID
}

func (g *Group) GetName() string {
	if g == nil {
		return ""
	}
	return g.Name
}

func (g *Group) GetType() GroupType {
	if g == nil {
		return ""
	}
	return g.Type
}

func (g *Group) GetAccessMode() *GroupAccessMode {
	if g == nil {
		return nil
	}
	return g.AccessMode
}

func (g *Group) GetGroupManagement() *GroupGroupManagement {
	if g == nil {
		return nil
	}
	return g.GroupManagement
}

func (g *Group) GetEnforceThreadedMode() *bool {
	if g == nil {
		return nil
	}
	return g.EnforceThreadedMode
}

func (g *Group) GetDateCreated() *time.Time {
	if g == nil {
		return nil
	}
	return g.DateCreated
}

func (g *Group) GetImageURL() *string {
	if g == nil {
		return nil
	}
	return g.ImageURL
}

func (g *Group) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *Group) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *Group) SetID(id string) {
	g.ID = id
	g.require(groupFieldID)
}

// SetChatID sets the ChatID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *Group) SetChatID(chatID *string) {
	g.ChatID = chatID
	g.require(groupFieldChatID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *Group) SetName(name string) {
	g.Name = name
	g.require(groupFieldName)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *Group) SetType(type_ GroupType) {
	g.Type = type_
	g.require(groupFieldType)
}

// SetAccessMode sets the AccessMode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *Group) SetAccessMode(accessMode *GroupAccessMode) {
	g.AccessMode = accessMode
	g.require(groupFieldAccessMode)
}

// SetGroupManagement sets the GroupManagement field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *Group) SetGroupManagement(groupManagement *GroupGroupManagement) {
	g.GroupManagement = groupManagement
	g.require(groupFieldGroupManagement)
}

// SetEnforceThreadedMode sets the EnforceThreadedMode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *Group) SetEnforceThreadedMode(enforceThreadedMode *bool) {
	g.EnforceThreadedMode = enforceThreadedMode
	g.require(groupFieldEnforceThreadedMode)
}

// SetDateCreated sets the DateCreated field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *Group) SetDateCreated(dateCreated *time.Time) {
	g.DateCreated = dateCreated
	g.require(groupFieldDateCreated)
}

// SetImageURL sets the ImageURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *Group) SetImageURL(imageURL *string) {
	g.ImageURL = imageURL
	g.require(groupFieldImageURL)
}

func (g *Group) UnmarshalJSON(data []byte) error {
	type embed Group
	var unmarshaler = struct {
		embed
		DateCreated *internal.DateTime `json:"dateCreated,omitempty"`
	}{
		embed: embed(*g),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*g = Group(unmarshaler.embed)
	g.DateCreated = unmarshaler.DateCreated.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *Group) MarshalJSON() ([]byte, error) {
	type embed Group
	var marshaler = struct {
		embed
		DateCreated *internal.DateTime `json:"dateCreated,omitempty"`
	}{
		embed:       embed(*g),
		DateCreated: internal.NewOptionalDateTime(g.DateCreated),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *Group) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

// Whether the group is public or private
type GroupAccessMode string

const (
	GroupAccessModePublic  GroupAccessMode = "public"
	GroupAccessModePrivate GroupAccessMode = "private"
)

func NewGroupAccessModeFromString(s string) (GroupAccessMode, error) {
	switch s {
	case "public":
		return GroupAccessModePublic, nil
	case "private":
		return GroupAccessModePrivate, nil
	}
	var t GroupAccessMode
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GroupAccessMode) Ptr() *GroupAccessMode {
	return &g
}

// Who can manage group settings and membership
type GroupGroupManagement string

const (
	GroupGroupManagementAllMembers      GroupGroupManagement = "allMembers"
	GroupGroupManagementGroupAdminsOnly GroupGroupManagement = "groupAdminsOnly"
)

func NewGroupGroupManagementFromString(s string) (GroupGroupManagement, error) {
	switch s {
	case "allMembers":
		return GroupGroupManagementAllMembers, nil
	case "groupAdminsOnly":
		return GroupGroupManagementGroupAdminsOnly, nil
	}
	var t GroupGroupManagement
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GroupGroupManagement) Ptr() *GroupGroupManagement {
	return &g
}

// A member of a group with their role
var (
	groupMemberFieldUserID = big.NewInt(1 << 0)
	groupMemberFieldRole   = big.NewInt(1 << 1)
)

type GroupMember struct {
	// The user's unique identifier
	UserID string `json:"userId" url:"userId"`
	// The member's role in the group
	Role GroupMemberRole `json:"role" url:"role"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GroupMember) GetUserID() string {
	if g == nil {
		return ""
	}
	return g.UserID
}

func (g *GroupMember) GetRole() GroupMemberRole {
	if g == nil {
		return ""
	}
	return g.Role
}

func (g *GroupMember) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GroupMember) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GroupMember) SetUserID(userID string) {
	g.UserID = userID
	g.require(groupMemberFieldUserID)
}

// SetRole sets the Role field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GroupMember) SetRole(role GroupMemberRole) {
	g.Role = role
	g.require(groupMemberFieldRole)
}

func (g *GroupMember) UnmarshalJSON(data []byte) error {
	type unmarshaler GroupMember
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GroupMember(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GroupMember) MarshalJSON() ([]byte, error) {
	type embed GroupMember
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GroupMember) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

// The member's role in the group
type GroupMemberRole string

const (
	GroupMemberRoleMember GroupMemberRole = "member"
	GroupMemberRoleAdmin  GroupMemberRole = "admin"
)

func NewGroupMemberRoleFromString(s string) (GroupMemberRole, error) {
	switch s {
	case "member":
		return GroupMemberRoleMember, nil
	case "admin":
		return GroupMemberRoleAdmin, nil
	}
	var t GroupMemberRole
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GroupMemberRole) Ptr() *GroupMemberRole {
	return &g
}

// The type of group:
// - `standard` - A regular channel created by users
// - `magicast` - A Magicast channel
// - `meeting` - A meeting channel
// - `roam` - The main Roam channel (one per workspace)
// - `onair` - An On-Air channel
// - `community` - A community channel
type GroupType string

const (
	GroupTypeStandard  GroupType = "standard"
	GroupTypeMagicast  GroupType = "magicast"
	GroupTypeMeeting   GroupType = "meeting"
	GroupTypeRoam      GroupType = "roam"
	GroupTypeOnair     GroupType = "onair"
	GroupTypeCommunity GroupType = "community"
)

func NewGroupTypeFromString(s string) (GroupType, error) {
	switch s {
	case "standard":
		return GroupTypeStandard, nil
	case "magicast":
		return GroupTypeMagicast, nil
	case "meeting":
		return GroupTypeMeeting, nil
	case "roam":
		return GroupTypeRoam, nil
	case "onair":
		return GroupTypeOnair, nil
	case "community":
		return GroupTypeCommunity, nil
	}
	var t GroupType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GroupType) Ptr() *GroupType {
	return &g
}

var (
	addGroupRequestMembersItemFieldUserID = big.NewInt(1 << 0)
	addGroupRequestMembersItemFieldRole   = big.NewInt(1 << 1)
)

type AddGroupRequestMembersItem struct {
	// User ID or email address
	UserID string `json:"userId" url:"userId"`
	// Role for this member
	Role AddGroupRequestMembersItemRole `json:"role" url:"role"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AddGroupRequestMembersItem) GetUserID() string {
	if a == nil {
		return ""
	}
	return a.UserID
}

func (a *AddGroupRequestMembersItem) GetRole() AddGroupRequestMembersItemRole {
	if a == nil {
		return ""
	}
	return a.Role
}

func (a *AddGroupRequestMembersItem) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *AddGroupRequestMembersItem) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddGroupRequestMembersItem) SetUserID(userID string) {
	a.UserID = userID
	a.require(addGroupRequestMembersItemFieldUserID)
}

// SetRole sets the Role field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddGroupRequestMembersItem) SetRole(role AddGroupRequestMembersItemRole) {
	a.Role = role
	a.require(addGroupRequestMembersItemFieldRole)
}

func (a *AddGroupRequestMembersItem) UnmarshalJSON(data []byte) error {
	type unmarshaler AddGroupRequestMembersItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AddGroupRequestMembersItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AddGroupRequestMembersItem) MarshalJSON() ([]byte, error) {
	type embed AddGroupRequestMembersItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AddGroupRequestMembersItem) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

// Role for this member
type AddGroupRequestMembersItemRole string

const (
	AddGroupRequestMembersItemRoleMember AddGroupRequestMembersItemRole = "member"
	AddGroupRequestMembersItemRoleAdmin  AddGroupRequestMembersItemRole = "admin"
)

func NewAddGroupRequestMembersItemRoleFromString(s string) (AddGroupRequestMembersItemRole, error) {
	switch s {
	case "member":
		return AddGroupRequestMembersItemRoleMember, nil
	case "admin":
		return AddGroupRequestMembersItemRoleAdmin, nil
	}
	var t AddGroupRequestMembersItemRole
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (a AddGroupRequestMembersItemRole) Ptr() *AddGroupRequestMembersItemRole {
	return &a
}

var (
	createGroupRequestMembersItemFieldUserID = big.NewInt(1 << 0)
	createGroupRequestMembersItemFieldRole   = big.NewInt(1 << 1)
)

type CreateGroupRequestMembersItem struct {
	// User ID or email address
	UserID string `json:"userId" url:"userId"`
	// Role for this member
	Role CreateGroupRequestMembersItemRole `json:"role" url:"role"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateGroupRequestMembersItem) GetUserID() string {
	if c == nil {
		return ""
	}
	return c.UserID
}

func (c *CreateGroupRequestMembersItem) GetRole() CreateGroupRequestMembersItemRole {
	if c == nil {
		return ""
	}
	return c.Role
}

func (c *CreateGroupRequestMembersItem) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreateGroupRequestMembersItem) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateGroupRequestMembersItem) SetUserID(userID string) {
	c.UserID = userID
	c.require(createGroupRequestMembersItemFieldUserID)
}

// SetRole sets the Role field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateGroupRequestMembersItem) SetRole(role CreateGroupRequestMembersItemRole) {
	c.Role = role
	c.require(createGroupRequestMembersItemFieldRole)
}

func (c *CreateGroupRequestMembersItem) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateGroupRequestMembersItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateGroupRequestMembersItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateGroupRequestMembersItem) MarshalJSON() ([]byte, error) {
	type embed CreateGroupRequestMembersItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateGroupRequestMembersItem) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// Role for this member
type CreateGroupRequestMembersItemRole string

const (
	CreateGroupRequestMembersItemRoleMember CreateGroupRequestMembersItemRole = "member"
	CreateGroupRequestMembersItemRoleAdmin  CreateGroupRequestMembersItemRole = "admin"
)

func NewCreateGroupRequestMembersItemRoleFromString(s string) (CreateGroupRequestMembersItemRole, error) {
	switch s {
	case "member":
		return CreateGroupRequestMembersItemRoleMember, nil
	case "admin":
		return CreateGroupRequestMembersItemRoleAdmin, nil
	}
	var t CreateGroupRequestMembersItemRole
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreateGroupRequestMembersItemRole) Ptr() *CreateGroupRequestMembersItemRole {
	return &c
}

var (
	listGroupResponseFieldGroups     = big.NewInt(1 << 0)
	listGroupResponseFieldNextCursor = big.NewInt(1 << 1)
)

type ListGroupResponse struct {
	Groups []*ListGroupResponseGroupsItem `json:"groups" url:"groups"`
	// Pagination cursor for the next page. Absent when there are no more results.
	NextCursor *string `json:"nextCursor,omitempty" url:"nextCursor,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListGroupResponse) GetGroups() []*ListGroupResponseGroupsItem {
	if l == nil {
		return nil
	}
	return l.Groups
}

func (l *ListGroupResponse) GetNextCursor() *string {
	if l == nil {
		return nil
	}
	return l.NextCursor
}

func (l *ListGroupResponse) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListGroupResponse) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetGroups sets the Groups field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListGroupResponse) SetGroups(groups []*ListGroupResponseGroupsItem) {
	l.Groups = groups
	l.require(listGroupResponseFieldGroups)
}

// SetNextCursor sets the NextCursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListGroupResponse) SetNextCursor(nextCursor *string) {
	l.NextCursor = nextCursor
	l.require(listGroupResponseFieldNextCursor)
}

func (l *ListGroupResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ListGroupResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListGroupResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListGroupResponse) MarshalJSON() ([]byte, error) {
	type embed ListGroupResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListGroupResponse) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

var (
	listGroupResponseGroupsItemFieldID          = big.NewInt(1 << 0)
	listGroupResponseGroupsItemFieldName        = big.NewInt(1 << 1)
	listGroupResponseGroupsItemFieldDescription = big.NewInt(1 << 2)
	listGroupResponseGroupsItemFieldImageURL    = big.NewInt(1 << 3)
	listGroupResponseGroupsItemFieldType        = big.NewInt(1 << 4)
	listGroupResponseGroupsItemFieldAccessMode  = big.NewInt(1 << 5)
	listGroupResponseGroupsItemFieldDateCreated = big.NewInt(1 << 6)
)

type ListGroupResponseGroupsItem struct {
	// The group ID.
	ID   string `json:"id" url:"id"`
	Name string `json:"name" url:"name"`
	// Group description, if set.
	Description *string `json:"description,omitempty" url:"description,omitempty"`
	// Group image URL, if set.
	ImageURL *string `json:"imageUrl,omitempty" url:"imageUrl,omitempty"`
	// Group type.
	Type ListGroupResponseGroupsItemType `json:"type" url:"type"`
	// Whether the group is public or private.
	AccessMode *ListGroupResponseGroupsItemAccessMode `json:"accessMode,omitempty" url:"accessMode,omitempty"`
	// When the group was created (RFC3339, caller's timezone).
	DateCreated *time.Time `json:"dateCreated,omitempty" url:"dateCreated,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListGroupResponseGroupsItem) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

func (l *ListGroupResponseGroupsItem) GetName() string {
	if l == nil {
		return ""
	}
	return l.Name
}

func (l *ListGroupResponseGroupsItem) GetDescription() *string {
	if l == nil {
		return nil
	}
	return l.Description
}

func (l *ListGroupResponseGroupsItem) GetImageURL() *string {
	if l == nil {
		return nil
	}
	return l.ImageURL
}

func (l *ListGroupResponseGroupsItem) GetType() ListGroupResponseGroupsItemType {
	if l == nil {
		return ""
	}
	return l.Type
}

func (l *ListGroupResponseGroupsItem) GetAccessMode() *ListGroupResponseGroupsItemAccessMode {
	if l == nil {
		return nil
	}
	return l.AccessMode
}

func (l *ListGroupResponseGroupsItem) GetDateCreated() *time.Time {
	if l == nil {
		return nil
	}
	return l.DateCreated
}

func (l *ListGroupResponseGroupsItem) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListGroupResponseGroupsItem) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListGroupResponseGroupsItem) SetID(id string) {
	l.ID = id
	l.require(listGroupResponseGroupsItemFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListGroupResponseGroupsItem) SetName(name string) {
	l.Name = name
	l.require(listGroupResponseGroupsItemFieldName)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListGroupResponseGroupsItem) SetDescription(description *string) {
	l.Description = description
	l.require(listGroupResponseGroupsItemFieldDescription)
}

// SetImageURL sets the ImageURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListGroupResponseGroupsItem) SetImageURL(imageURL *string) {
	l.ImageURL = imageURL
	l.require(listGroupResponseGroupsItemFieldImageURL)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListGroupResponseGroupsItem) SetType(type_ ListGroupResponseGroupsItemType) {
	l.Type = type_
	l.require(listGroupResponseGroupsItemFieldType)
}

// SetAccessMode sets the AccessMode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListGroupResponseGroupsItem) SetAccessMode(accessMode *ListGroupResponseGroupsItemAccessMode) {
	l.AccessMode = accessMode
	l.require(listGroupResponseGroupsItemFieldAccessMode)
}

// SetDateCreated sets the DateCreated field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListGroupResponseGroupsItem) SetDateCreated(dateCreated *time.Time) {
	l.DateCreated = dateCreated
	l.require(listGroupResponseGroupsItemFieldDateCreated)
}

func (l *ListGroupResponseGroupsItem) UnmarshalJSON(data []byte) error {
	type embed ListGroupResponseGroupsItem
	var unmarshaler = struct {
		embed
		DateCreated *internal.DateTime `json:"dateCreated,omitempty"`
	}{
		embed: embed(*l),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*l = ListGroupResponseGroupsItem(unmarshaler.embed)
	l.DateCreated = unmarshaler.DateCreated.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListGroupResponseGroupsItem) MarshalJSON() ([]byte, error) {
	type embed ListGroupResponseGroupsItem
	var marshaler = struct {
		embed
		DateCreated *internal.DateTime `json:"dateCreated,omitempty"`
	}{
		embed:       embed(*l),
		DateCreated: internal.NewOptionalDateTime(l.DateCreated),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListGroupResponseGroupsItem) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

// Whether the group is public or private.
type ListGroupResponseGroupsItemAccessMode string

const (
	ListGroupResponseGroupsItemAccessModePublic  ListGroupResponseGroupsItemAccessMode = "public"
	ListGroupResponseGroupsItemAccessModePrivate ListGroupResponseGroupsItemAccessMode = "private"
)

func NewListGroupResponseGroupsItemAccessModeFromString(s string) (ListGroupResponseGroupsItemAccessMode, error) {
	switch s {
	case "public":
		return ListGroupResponseGroupsItemAccessModePublic, nil
	case "private":
		return ListGroupResponseGroupsItemAccessModePrivate, nil
	}
	var t ListGroupResponseGroupsItemAccessMode
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (l ListGroupResponseGroupsItemAccessMode) Ptr() *ListGroupResponseGroupsItemAccessMode {
	return &l
}

// Group type.
type ListGroupResponseGroupsItemType string

const (
	ListGroupResponseGroupsItemTypeStandard  ListGroupResponseGroupsItemType = "standard"
	ListGroupResponseGroupsItemTypeMagicast  ListGroupResponseGroupsItemType = "magicast"
	ListGroupResponseGroupsItemTypeMeeting   ListGroupResponseGroupsItemType = "meeting"
	ListGroupResponseGroupsItemTypeRoam      ListGroupResponseGroupsItemType = "roam"
	ListGroupResponseGroupsItemTypeOnair     ListGroupResponseGroupsItemType = "onair"
	ListGroupResponseGroupsItemTypeCommunity ListGroupResponseGroupsItemType = "community"
)

func NewListGroupResponseGroupsItemTypeFromString(s string) (ListGroupResponseGroupsItemType, error) {
	switch s {
	case "standard":
		return ListGroupResponseGroupsItemTypeStandard, nil
	case "magicast":
		return ListGroupResponseGroupsItemTypeMagicast, nil
	case "meeting":
		return ListGroupResponseGroupsItemTypeMeeting, nil
	case "roam":
		return ListGroupResponseGroupsItemTypeRoam, nil
	case "onair":
		return ListGroupResponseGroupsItemTypeOnair, nil
	case "community":
		return ListGroupResponseGroupsItemTypeCommunity, nil
	}
	var t ListGroupResponseGroupsItemType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (l ListGroupResponseGroupsItemType) Ptr() *ListGroupResponseGroupsItemType {
	return &l
}

var (
	membersGroupResponseFieldMembers    = big.NewInt(1 << 0)
	membersGroupResponseFieldNextCursor = big.NewInt(1 << 1)
)

type MembersGroupResponse struct {
	Members []*GroupMember `json:"members,omitempty" url:"members,omitempty"`
	// Pagination cursor for fetching the next page of results
	NextCursor *string `json:"nextCursor,omitempty" url:"nextCursor,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MembersGroupResponse) GetMembers() []*GroupMember {
	if m == nil {
		return nil
	}
	return m.Members
}

func (m *MembersGroupResponse) GetNextCursor() *string {
	if m == nil {
		return nil
	}
	return m.NextCursor
}

func (m *MembersGroupResponse) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.extraProperties
}

func (m *MembersGroupResponse) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetMembers sets the Members field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MembersGroupResponse) SetMembers(members []*GroupMember) {
	m.Members = members
	m.require(membersGroupResponseFieldMembers)
}

// SetNextCursor sets the NextCursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MembersGroupResponse) SetNextCursor(nextCursor *string) {
	m.NextCursor = nextCursor
	m.require(membersGroupResponseFieldNextCursor)
}

func (m *MembersGroupResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler MembersGroupResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MembersGroupResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MembersGroupResponse) MarshalJSON() ([]byte, error) {
	type embed MembersGroupResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *MembersGroupResponse) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}
