// Code generated by Fern. DO NOT EDIT.

package roamhq

import (
	json "encoding/json"
	fmt "fmt"
	big "math/big"
	internal "ro.am/roamhq/internal"
	time "time"
)

var (
	listLobbyRequestFieldHandle = big.NewInt(1 << 0)
)

type ListLobbyRequest struct {
	// Filter by lobby handle (first path segment), e.g., `robfig` for
	// `ro.am/robfig` or `ro.am/robfig/tour`.
	Handle *string `json:"-" url:"handle,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListLobbyRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetHandle sets the Handle field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListLobbyRequest) SetHandle(handle *string) {
	l.Handle = handle
	l.require(listLobbyRequestFieldHandle)
}

var (
	listBookingsLobbyRequestFieldLobbyID = big.NewInt(1 << 0)
	listBookingsLobbyRequestFieldAfter   = big.NewInt(1 << 1)
	listBookingsLobbyRequestFieldBefore  = big.NewInt(1 << 2)
	listBookingsLobbyRequestFieldLimit   = big.NewInt(1 << 3)
	listBookingsLobbyRequestFieldCursor  = big.NewInt(1 << 4)
)

type ListBookingsLobbyRequest struct {
	// The lobby configuration ID to list bookings for.
	LobbyID string `json:"-" url:"lobbyId"`
	// The datetime to begin listing bookings (YYYY-MM-DD or RFC-3339).
	// Defaults to "no filter".
	After *time.Time `json:"-" url:"after,omitempty"`
	// The datetime until which to list bookings (YYYY-MM-DD or RFC-3339).
	// Defaults to "now".
	Before *time.Time `json:"-" url:"before,omitempty"`
	// The number of bookings to return per response. Default is 10.
	Limit *int `json:"-" url:"limit,omitempty"`
	// Opaque pagination cursor from a previous response's `nextCursor`. Do not construct cursors manually.
	Cursor *string `json:"-" url:"cursor,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListBookingsLobbyRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetLobbyID sets the LobbyID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListBookingsLobbyRequest) SetLobbyID(lobbyID string) {
	l.LobbyID = lobbyID
	l.require(listBookingsLobbyRequestFieldLobbyID)
}

// SetAfter sets the After field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListBookingsLobbyRequest) SetAfter(after *time.Time) {
	l.After = after
	l.require(listBookingsLobbyRequestFieldAfter)
}

// SetBefore sets the Before field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListBookingsLobbyRequest) SetBefore(before *time.Time) {
	l.Before = before
	l.require(listBookingsLobbyRequestFieldBefore)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListBookingsLobbyRequest) SetLimit(limit *int) {
	l.Limit = limit
	l.require(listBookingsLobbyRequestFieldLimit)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListBookingsLobbyRequest) SetCursor(cursor *string) {
	l.Cursor = cursor
	l.require(listBookingsLobbyRequestFieldCursor)
}

var (
	lobbyBookingFieldID          = big.NewInt(1 << 0)
	lobbyBookingFieldStart       = big.NewInt(1 << 1)
	lobbyBookingFieldEnd         = big.NewInt(1 << 2)
	lobbyBookingFieldStatus      = big.NewInt(1 << 3)
	lobbyBookingFieldTimeZone    = big.NewInt(1 << 4)
	lobbyBookingFieldNotes       = big.NewInt(1 << 5)
	lobbyBookingFieldCreated     = big.NewInt(1 << 6)
	lobbyBookingFieldHosts       = big.NewInt(1 << 7)
	lobbyBookingFieldInvitees    = big.NewInt(1 << 8)
	lobbyBookingFieldResponses   = big.NewInt(1 << 9)
	lobbyBookingFieldMeetingLink = big.NewInt(1 << 10)
)

type LobbyBooking struct {
	// Unique booking identifier
	ID string `json:"id" url:"id"`
	// Start time in RFC3339
	Start time.Time `json:"start" url:"start"`
	// End time in RFC3339
	End time.Time `json:"end" url:"end"`
	// Current status of the booking
	Status string `json:"status" url:"status"`
	// IANA time zone of the booking times
	TimeZone *string `json:"timeZone,omitempty" url:"timeZone,omitempty"`
	// Optional notes provided by the booker
	Notes *string `json:"notes,omitempty" url:"notes,omitempty"`
	// Creation time
	Created  *time.Time             `json:"created,omitempty" url:"created,omitempty"`
	Hosts    []*LobbyBookingHost    `json:"hosts,omitempty" url:"hosts,omitempty"`
	Invitees []*LobbyBookingInvitee `json:"invitees,omitempty" url:"invitees,omitempty"`
	// The guest's answers to the lobby's custom questions, including hidden fields
	// populated from URL query parameters on the lobby link. One entry per answered
	// question; empty or absent when the guest answered no custom questions.
	Responses []*LobbyBookingResponse `json:"responses,omitempty" url:"responses,omitempty"`
	// Meeting link URL, used to join the meeting
	MeetingLink *string `json:"meetingLink,omitempty" url:"meetingLink,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *LobbyBooking) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

func (l *LobbyBooking) GetStart() time.Time {
	if l == nil {
		return time.Time{}
	}
	return l.Start
}

func (l *LobbyBooking) GetEnd() time.Time {
	if l == nil {
		return time.Time{}
	}
	return l.End
}

func (l *LobbyBooking) GetStatus() string {
	if l == nil {
		return ""
	}
	return l.Status
}

func (l *LobbyBooking) GetTimeZone() *string {
	if l == nil {
		return nil
	}
	return l.TimeZone
}

func (l *LobbyBooking) GetNotes() *string {
	if l == nil {
		return nil
	}
	return l.Notes
}

func (l *LobbyBooking) GetCreated() *time.Time {
	if l == nil {
		return nil
	}
	return l.Created
}

func (l *LobbyBooking) GetHosts() []*LobbyBookingHost {
	if l == nil {
		return nil
	}
	return l.Hosts
}

func (l *LobbyBooking) GetInvitees() []*LobbyBookingInvitee {
	if l == nil {
		return nil
	}
	return l.Invitees
}

func (l *LobbyBooking) GetResponses() []*LobbyBookingResponse {
	if l == nil {
		return nil
	}
	return l.Responses
}

func (l *LobbyBooking) GetMeetingLink() *string {
	if l == nil {
		return nil
	}
	return l.MeetingLink
}

func (l *LobbyBooking) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *LobbyBooking) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LobbyBooking) SetID(id string) {
	l.ID = id
	l.require(lobbyBookingFieldID)
}

// SetStart sets the Start field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LobbyBooking) SetStart(start time.Time) {
	l.Start = start
	l.require(lobbyBookingFieldStart)
}

// SetEnd sets the End field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LobbyBooking) SetEnd(end time.Time) {
	l.End = end
	l.require(lobbyBookingFieldEnd)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LobbyBooking) SetStatus(status string) {
	l.Status = status
	l.require(lobbyBookingFieldStatus)
}

// SetTimeZone sets the TimeZone field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LobbyBooking) SetTimeZone(timeZone *string) {
	l.TimeZone = timeZone
	l.require(lobbyBookingFieldTimeZone)
}

// SetNotes sets the Notes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LobbyBooking) SetNotes(notes *string) {
	l.Notes = notes
	l.require(lobbyBookingFieldNotes)
}

// SetCreated sets the Created field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LobbyBooking) SetCreated(created *time.Time) {
	l.Created = created
	l.require(lobbyBookingFieldCreated)
}

// SetHosts sets the Hosts field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LobbyBooking) SetHosts(hosts []*LobbyBookingHost) {
	l.Hosts = hosts
	l.require(lobbyBookingFieldHosts)
}

// SetInvitees sets the Invitees field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LobbyBooking) SetInvitees(invitees []*LobbyBookingInvitee) {
	l.Invitees = invitees
	l.require(lobbyBookingFieldInvitees)
}

// SetResponses sets the Responses field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LobbyBooking) SetResponses(responses []*LobbyBookingResponse) {
	l.Responses = responses
	l.require(lobbyBookingFieldResponses)
}

// SetMeetingLink sets the MeetingLink field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LobbyBooking) SetMeetingLink(meetingLink *string) {
	l.MeetingLink = meetingLink
	l.require(lobbyBookingFieldMeetingLink)
}

func (l *LobbyBooking) UnmarshalJSON(data []byte) error {
	type embed LobbyBooking
	var unmarshaler = struct {
		embed
		Start   *internal.DateTime `json:"start"`
		End     *internal.DateTime `json:"end"`
		Created *internal.DateTime `json:"created,omitempty"`
	}{
		embed: embed(*l),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*l = LobbyBooking(unmarshaler.embed)
	l.Start = unmarshaler.Start.Time()
	l.End = unmarshaler.End.Time()
	l.Created = unmarshaler.Created.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *LobbyBooking) MarshalJSON() ([]byte, error) {
	type embed LobbyBooking
	var marshaler = struct {
		embed
		Start   *internal.DateTime `json:"start"`
		End     *internal.DateTime `json:"end"`
		Created *internal.DateTime `json:"created,omitempty"`
	}{
		embed:   embed(*l),
		Start:   internal.NewDateTime(l.Start),
		End:     internal.NewDateTime(l.End),
		Created: internal.NewOptionalDateTime(l.Created),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *LobbyBooking) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

var (
	lobbyBookingHostFieldName        = big.NewInt(1 << 0)
	lobbyBookingHostFieldEmail       = big.NewInt(1 << 1)
	lobbyBookingHostFieldIsOrganizer = big.NewInt(1 << 2)
)

type LobbyBookingHost struct {
	// Display name of the host
	Name *string `json:"name,omitempty" url:"name,omitempty"`
	// Email address of the host
	Email string `json:"email" url:"email"`
	// Whether this host is the organizer
	IsOrganizer bool `json:"isOrganizer" url:"isOrganizer"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *LobbyBookingHost) GetName() *string {
	if l == nil {
		return nil
	}
	return l.Name
}

func (l *LobbyBookingHost) GetEmail() string {
	if l == nil {
		return ""
	}
	return l.Email
}

func (l *LobbyBookingHost) GetIsOrganizer() bool {
	if l == nil {
		return false
	}
	return l.IsOrganizer
}

func (l *LobbyBookingHost) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *LobbyBookingHost) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LobbyBookingHost) SetName(name *string) {
	l.Name = name
	l.require(lobbyBookingHostFieldName)
}

// SetEmail sets the Email field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LobbyBookingHost) SetEmail(email string) {
	l.Email = email
	l.require(lobbyBookingHostFieldEmail)
}

// SetIsOrganizer sets the IsOrganizer field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LobbyBookingHost) SetIsOrganizer(isOrganizer bool) {
	l.IsOrganizer = isOrganizer
	l.require(lobbyBookingHostFieldIsOrganizer)
}

func (l *LobbyBookingHost) UnmarshalJSON(data []byte) error {
	type unmarshaler LobbyBookingHost
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = LobbyBookingHost(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *LobbyBookingHost) MarshalJSON() ([]byte, error) {
	type embed LobbyBookingHost
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *LobbyBookingHost) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

var (
	lobbyBookingInviteeFieldName     = big.NewInt(1 << 0)
	lobbyBookingInviteeFieldEmail    = big.NewInt(1 << 1)
	lobbyBookingInviteeFieldStatus   = big.NewInt(1 << 2)
	lobbyBookingInviteeFieldIsBooker = big.NewInt(1 << 3)
)

type LobbyBookingInvitee struct {
	// Display name of the invitee
	Name *string `json:"name,omitempty" url:"name,omitempty"`
	// Email address of the invitee
	Email string `json:"email" url:"email"`
	// Invitee's RSVP or booking status
	Status string `json:"status" url:"status"`
	// Whether this invitee created the booking
	IsBooker *bool `json:"isBooker,omitempty" url:"isBooker,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *LobbyBookingInvitee) GetName() *string {
	if l == nil {
		return nil
	}
	return l.Name
}

func (l *LobbyBookingInvitee) GetEmail() string {
	if l == nil {
		return ""
	}
	return l.Email
}

func (l *LobbyBookingInvitee) GetStatus() string {
	if l == nil {
		return ""
	}
	return l.Status
}

func (l *LobbyBookingInvitee) GetIsBooker() *bool {
	if l == nil {
		return nil
	}
	return l.IsBooker
}

func (l *LobbyBookingInvitee) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *LobbyBookingInvitee) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LobbyBookingInvitee) SetName(name *string) {
	l.Name = name
	l.require(lobbyBookingInviteeFieldName)
}

// SetEmail sets the Email field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LobbyBookingInvitee) SetEmail(email string) {
	l.Email = email
	l.require(lobbyBookingInviteeFieldEmail)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LobbyBookingInvitee) SetStatus(status string) {
	l.Status = status
	l.require(lobbyBookingInviteeFieldStatus)
}

// SetIsBooker sets the IsBooker field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LobbyBookingInvitee) SetIsBooker(isBooker *bool) {
	l.IsBooker = isBooker
	l.require(lobbyBookingInviteeFieldIsBooker)
}

func (l *LobbyBookingInvitee) UnmarshalJSON(data []byte) error {
	type unmarshaler LobbyBookingInvitee
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = LobbyBookingInvitee(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *LobbyBookingInvitee) MarshalJSON() ([]byte, error) {
	type embed LobbyBookingInvitee
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *LobbyBookingInvitee) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

// A guest's answer to one of the lobby's custom questions, captured when the booking
// was made. Includes answers to hidden fields, which are populated from URL query
// parameters on the lobby link (e.g. `?utm_source=partner`).
var (
	lobbyBookingResponseFieldFieldID  = big.NewInt(1 << 0)
	lobbyBookingResponseFieldKey      = big.NewInt(1 << 1)
	lobbyBookingResponseFieldQuestion = big.NewInt(1 << 2)
	lobbyBookingResponseFieldType     = big.NewInt(1 << 3)
	lobbyBookingResponseFieldValue    = big.NewInt(1 << 4)
)

type LobbyBookingResponse struct {
	// ID of the custom field (question) this answer belongs to.
	FieldID string `json:"fieldId" url:"fieldId"`
	// The field's stable key, if the lobby owner assigned one, as captured when the
	// booking was made. For hidden fields this is the URL query parameter name used to
	// populate the value.
	Key *string `json:"key,omitempty" url:"key,omitempty"`
	// The question's display name. Omitted if the field definition can no longer be
	// found on the lobby configuration.
	Question *string `json:"question,omitempty" url:"question,omitempty"`
	// The custom field type. Omitted when `question` is omitted.
	Type *LobbyBookingResponseType `json:"type,omitempty" url:"type,omitempty"`
	// The human-readable answer. For option fields (radio, checkbox, dropdown) this is
	// the selected option label(s), not internal option IDs. Checkbox answers are
	// arrays of strings; all other answers are strings.
	Value *LobbyBookingResponseValue `json:"value,omitempty" url:"value,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *LobbyBookingResponse) GetFieldID() string {
	if l == nil {
		return ""
	}
	return l.FieldID
}

func (l *LobbyBookingResponse) GetKey() *string {
	if l == nil {
		return nil
	}
	return l.Key
}

func (l *LobbyBookingResponse) GetQuestion() *string {
	if l == nil {
		return nil
	}
	return l.Question
}

func (l *LobbyBookingResponse) GetType() *LobbyBookingResponseType {
	if l == nil {
		return nil
	}
	return l.Type
}

func (l *LobbyBookingResponse) GetValue() *LobbyBookingResponseValue {
	if l == nil {
		return nil
	}
	return l.Value
}

func (l *LobbyBookingResponse) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *LobbyBookingResponse) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetFieldID sets the FieldID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LobbyBookingResponse) SetFieldID(fieldID string) {
	l.FieldID = fieldID
	l.require(lobbyBookingResponseFieldFieldID)
}

// SetKey sets the Key field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LobbyBookingResponse) SetKey(key *string) {
	l.Key = key
	l.require(lobbyBookingResponseFieldKey)
}

// SetQuestion sets the Question field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LobbyBookingResponse) SetQuestion(question *string) {
	l.Question = question
	l.require(lobbyBookingResponseFieldQuestion)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LobbyBookingResponse) SetType(type_ *LobbyBookingResponseType) {
	l.Type = type_
	l.require(lobbyBookingResponseFieldType)
}

// SetValue sets the Value field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LobbyBookingResponse) SetValue(value *LobbyBookingResponseValue) {
	l.Value = value
	l.require(lobbyBookingResponseFieldValue)
}

func (l *LobbyBookingResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler LobbyBookingResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = LobbyBookingResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *LobbyBookingResponse) MarshalJSON() ([]byte, error) {
	type embed LobbyBookingResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *LobbyBookingResponse) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

// The custom field type. Omitted when `question` is omitted.
type LobbyBookingResponseType string

const (
	LobbyBookingResponseTypeShortText   LobbyBookingResponseType = "short_text"
	LobbyBookingResponseTypeText        LobbyBookingResponseType = "text"
	LobbyBookingResponseTypeEmail       LobbyBookingResponseType = "email"
	LobbyBookingResponseTypePhoneNumber LobbyBookingResponseType = "phone_number"
	LobbyBookingResponseTypeRadio       LobbyBookingResponseType = "radio"
	LobbyBookingResponseTypeCheckbox    LobbyBookingResponseType = "checkbox"
	LobbyBookingResponseTypeDropdown    LobbyBookingResponseType = "dropdown"
	LobbyBookingResponseTypeHidden      LobbyBookingResponseType = "hidden"
)

func NewLobbyBookingResponseTypeFromString(s string) (LobbyBookingResponseType, error) {
	switch s {
	case "short_text":
		return LobbyBookingResponseTypeShortText, nil
	case "text":
		return LobbyBookingResponseTypeText, nil
	case "email":
		return LobbyBookingResponseTypeEmail, nil
	case "phone_number":
		return LobbyBookingResponseTypePhoneNumber, nil
	case "radio":
		return LobbyBookingResponseTypeRadio, nil
	case "checkbox":
		return LobbyBookingResponseTypeCheckbox, nil
	case "dropdown":
		return LobbyBookingResponseTypeDropdown, nil
	case "hidden":
		return LobbyBookingResponseTypeHidden, nil
	}
	var t LobbyBookingResponseType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (l LobbyBookingResponseType) Ptr() *LobbyBookingResponseType {
	return &l
}

// The human-readable answer. For option fields (radio, checkbox, dropdown) this is
// the selected option label(s), not internal option IDs. Checkbox answers are
// arrays of strings; all other answers are strings.
type LobbyBookingResponseValue struct {
	String     string
	StringList []string

	typ string
}

func (l *LobbyBookingResponseValue) GetString() string {
	if l == nil {
		return ""
	}
	return l.String
}

func (l *LobbyBookingResponseValue) GetStringList() []string {
	if l == nil {
		return nil
	}
	return l.StringList
}

func (l *LobbyBookingResponseValue) UnmarshalJSON(data []byte) error {
	var valueString string
	if err := json.Unmarshal(data, &valueString); err == nil {
		l.typ = "String"
		l.String = valueString
		return nil
	}
	var valueStringList []string
	if err := json.Unmarshal(data, &valueStringList); err == nil {
		l.typ = "StringList"
		l.StringList = valueStringList
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, l)
}

func (l LobbyBookingResponseValue) MarshalJSON() ([]byte, error) {
	if l.typ == "String" || l.String != "" {
		return json.Marshal(l.String)
	}
	if l.typ == "StringList" || l.StringList != nil {
		return json.Marshal(l.StringList)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", l)
}

type LobbyBookingResponseValueVisitor interface {
	VisitString(string) error
	VisitStringList([]string) error
}

func (l *LobbyBookingResponseValue) Accept(visitor LobbyBookingResponseValueVisitor) error {
	if l.typ == "String" || l.String != "" {
		return visitor.VisitString(l.String)
	}
	if l.typ == "StringList" || l.StringList != nil {
		return visitor.VisitStringList(l.StringList)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", l)
}

var (
	listBookingsLobbyResponseFieldBookings   = big.NewInt(1 << 0)
	listBookingsLobbyResponseFieldNextCursor = big.NewInt(1 << 1)
)

type ListBookingsLobbyResponse struct {
	Bookings []*LobbyBooking `json:"bookings,omitempty" url:"bookings,omitempty"`
	// Returned if there is a subsequent page of bookings.
	NextCursor *string `json:"nextCursor,omitempty" url:"nextCursor,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListBookingsLobbyResponse) GetBookings() []*LobbyBooking {
	if l == nil {
		return nil
	}
	return l.Bookings
}

func (l *ListBookingsLobbyResponse) GetNextCursor() *string {
	if l == nil {
		return nil
	}
	return l.NextCursor
}

func (l *ListBookingsLobbyResponse) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListBookingsLobbyResponse) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetBookings sets the Bookings field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListBookingsLobbyResponse) SetBookings(bookings []*LobbyBooking) {
	l.Bookings = bookings
	l.require(listBookingsLobbyResponseFieldBookings)
}

// SetNextCursor sets the NextCursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListBookingsLobbyResponse) SetNextCursor(nextCursor *string) {
	l.NextCursor = nextCursor
	l.require(listBookingsLobbyResponseFieldNextCursor)
}

func (l *ListBookingsLobbyResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ListBookingsLobbyResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListBookingsLobbyResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListBookingsLobbyResponse) MarshalJSON() ([]byte, error) {
	type embed ListBookingsLobbyResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListBookingsLobbyResponse) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

var (
	listLobbyResponseFieldLobbies = big.NewInt(1 << 0)
)

type ListLobbyResponse struct {
	Lobbies []*ListLobbyResponseLobbiesItem `json:"lobbies,omitempty" url:"lobbies,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListLobbyResponse) GetLobbies() []*ListLobbyResponseLobbiesItem {
	if l == nil {
		return nil
	}
	return l.Lobbies
}

func (l *ListLobbyResponse) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListLobbyResponse) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetLobbies sets the Lobbies field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListLobbyResponse) SetLobbies(lobbies []*ListLobbyResponseLobbiesItem) {
	l.Lobbies = lobbies
	l.require(listLobbyResponseFieldLobbies)
}

func (l *ListLobbyResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ListLobbyResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListLobbyResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListLobbyResponse) MarshalJSON() ([]byte, error) {
	type embed ListLobbyResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListLobbyResponse) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

var (
	listLobbyResponseLobbiesItemFieldID          = big.NewInt(1 << 0)
	listLobbyResponseLobbiesItemFieldSlug        = big.NewInt(1 << 1)
	listLobbyResponseLobbiesItemFieldDisplayName = big.NewInt(1 << 2)
	listLobbyResponseLobbiesItemFieldActive      = big.NewInt(1 << 3)
	listLobbyResponseLobbiesItemFieldURL         = big.NewInt(1 << 4)
	listLobbyResponseLobbiesItemFieldHandle      = big.NewInt(1 << 5)
)

type ListLobbyResponseLobbiesItem struct {
	// Unique identifier of the lobby configuration (UUID)
	ID *string `json:"id,omitempty" url:"id,omitempty"`
	// Optional second path segment for the lobby. May be empty.
	Slug *string `json:"slug,omitempty" url:"slug,omitempty"`
	// Human-readable name of the lobby configuration
	DisplayName *string `json:"displayName,omitempty" url:"displayName,omitempty"`
	// Whether the lobby configuration is active
	Active *bool `json:"active,omitempty" url:"active,omitempty"`
	// Public URL of the lobby (e.g., `https://ro.am/handle` or `https://ro.am/handle/slug`)
	URL *string `json:"url,omitempty" url:"url,omitempty"`
	// First path segment of the lobby URL
	Handle *string `json:"handle,omitempty" url:"handle,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListLobbyResponseLobbiesItem) GetID() *string {
	if l == nil {
		return nil
	}
	return l.ID
}

func (l *ListLobbyResponseLobbiesItem) GetSlug() *string {
	if l == nil {
		return nil
	}
	return l.Slug
}

func (l *ListLobbyResponseLobbiesItem) GetDisplayName() *string {
	if l == nil {
		return nil
	}
	return l.DisplayName
}

func (l *ListLobbyResponseLobbiesItem) GetActive() *bool {
	if l == nil {
		return nil
	}
	return l.Active
}

func (l *ListLobbyResponseLobbiesItem) GetURL() *string {
	if l == nil {
		return nil
	}
	return l.URL
}

func (l *ListLobbyResponseLobbiesItem) GetHandle() *string {
	if l == nil {
		return nil
	}
	return l.Handle
}

func (l *ListLobbyResponseLobbiesItem) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListLobbyResponseLobbiesItem) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListLobbyResponseLobbiesItem) SetID(id *string) {
	l.ID = id
	l.require(listLobbyResponseLobbiesItemFieldID)
}

// SetSlug sets the Slug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListLobbyResponseLobbiesItem) SetSlug(slug *string) {
	l.Slug = slug
	l.require(listLobbyResponseLobbiesItemFieldSlug)
}

// SetDisplayName sets the DisplayName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListLobbyResponseLobbiesItem) SetDisplayName(displayName *string) {
	l.DisplayName = displayName
	l.require(listLobbyResponseLobbiesItemFieldDisplayName)
}

// SetActive sets the Active field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListLobbyResponseLobbiesItem) SetActive(active *bool) {
	l.Active = active
	l.require(listLobbyResponseLobbiesItemFieldActive)
}

// SetURL sets the URL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListLobbyResponseLobbiesItem) SetURL(url *string) {
	l.URL = url
	l.require(listLobbyResponseLobbiesItemFieldURL)
}

// SetHandle sets the Handle field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListLobbyResponseLobbiesItem) SetHandle(handle *string) {
	l.Handle = handle
	l.require(listLobbyResponseLobbiesItemFieldHandle)
}

func (l *ListLobbyResponseLobbiesItem) UnmarshalJSON(data []byte) error {
	type unmarshaler ListLobbyResponseLobbiesItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListLobbyResponseLobbiesItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListLobbyResponseLobbiesItem) MarshalJSON() ([]byte, error) {
	type embed ListLobbyResponseLobbiesItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListLobbyResponseLobbiesItem) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}
