// Code generated by Fern. DO NOT EDIT.

package roamhq

import (
	json "encoding/json"
	fmt "fmt"
	big "math/big"
	internal "ro.am/roamhq/internal"
	time "time"
)

var (
	recordingListRequestFieldAfter  = big.NewInt(1 << 0)
	recordingListRequestFieldBefore = big.NewInt(1 << 1)
	recordingListRequestFieldLimit  = big.NewInt(1 << 2)
	recordingListRequestFieldCursor = big.NewInt(1 << 3)
)

type RecordingListRequest struct {
	// The datetime to begin listing recordings (YYYY-MM-DD or RFC-3339).
	// Defaults to "no filter".
	After *string `json:"-" url:"after,omitempty"`
	// The datetime until which to list recordings (YYYY-MM-DD or RFC-3339).
	// Defaults to "now".
	Before *string `json:"-" url:"before,omitempty"`
	// The number of recordings to return per response. Default is 10.
	Limit *int `json:"-" url:"limit,omitempty"`
	// Opaque pagination cursor from a previous response's `nextCursor`. Do not construct cursors manually.
	Cursor *string `json:"-" url:"cursor,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *RecordingListRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetAfter sets the After field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RecordingListRequest) SetAfter(after *string) {
	r.After = after
	r.require(recordingListRequestFieldAfter)
}

// SetBefore sets the Before field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RecordingListRequest) SetBefore(before *string) {
	r.Before = before
	r.require(recordingListRequestFieldBefore)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RecordingListRequest) SetLimit(limit *int) {
	r.Limit = limit
	r.require(recordingListRequestFieldLimit)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RecordingListRequest) SetCursor(cursor *string) {
	r.Cursor = cursor
	r.require(recordingListRequestFieldCursor)
}

var (
	recordingListResponseFieldRecordings = big.NewInt(1 << 0)
	recordingListResponseFieldNextCursor = big.NewInt(1 << 1)
)

type RecordingListResponse struct {
	Recordings []*RecordingListResponseRecordingsItem `json:"recordings,omitempty" url:"recordings,omitempty"`
	// Returned if there is a subsequent page of recordings.
	NextCursor *string `json:"nextCursor,omitempty" url:"nextCursor,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RecordingListResponse) GetRecordings() []*RecordingListResponseRecordingsItem {
	if r == nil {
		return nil
	}
	return r.Recordings
}

func (r *RecordingListResponse) GetNextCursor() *string {
	if r == nil {
		return nil
	}
	return r.NextCursor
}

func (r *RecordingListResponse) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *RecordingListResponse) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetRecordings sets the Recordings field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RecordingListResponse) SetRecordings(recordings []*RecordingListResponseRecordingsItem) {
	r.Recordings = recordings
	r.require(recordingListResponseFieldRecordings)
}

// SetNextCursor sets the NextCursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RecordingListResponse) SetNextCursor(nextCursor *string) {
	r.NextCursor = nextCursor
	r.require(recordingListResponseFieldNextCursor)
}

func (r *RecordingListResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler RecordingListResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RecordingListResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RecordingListResponse) MarshalJSON() ([]byte, error) {
	type embed RecordingListResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RecordingListResponse) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

var (
	recordingListResponseRecordingsItemFieldRecordingID = big.NewInt(1 << 0)
	recordingListResponseRecordingsItemFieldLocation    = big.NewInt(1 << 1)
	recordingListResponseRecordingsItemFieldStartTime   = big.NewInt(1 << 2)
	recordingListResponseRecordingsItemFieldEndTime     = big.NewInt(1 << 3)
	recordingListResponseRecordingsItemFieldVideoURL    = big.NewInt(1 << 4)
)

type RecordingListResponseRecordingsItem struct {
	// A unique identifier for the recording
	RecordingID *string `json:"recordingId,omitempty" url:"recordingId,omitempty"`
	// Name of the Roam room where the recording took place
	Location *string `json:"location,omitempty" url:"location,omitempty"`
	// Exact time when the recording began
	StartTime *time.Time `json:"startTime,omitempty" url:"startTime,omitempty"`
	// Exact time when the recording stopped
	EndTime *time.Time `json:"endTime,omitempty" url:"endTime,omitempty"`
	// URL where the video file may be downloaded
	VideoURL *string `json:"videoUrl,omitempty" url:"videoUrl,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RecordingListResponseRecordingsItem) GetRecordingID() *string {
	if r == nil {
		return nil
	}
	return r.RecordingID
}

func (r *RecordingListResponseRecordingsItem) GetLocation() *string {
	if r == nil {
		return nil
	}
	return r.Location
}

func (r *RecordingListResponseRecordingsItem) GetStartTime() *time.Time {
	if r == nil {
		return nil
	}
	return r.StartTime
}

func (r *RecordingListResponseRecordingsItem) GetEndTime() *time.Time {
	if r == nil {
		return nil
	}
	return r.EndTime
}

func (r *RecordingListResponseRecordingsItem) GetVideoURL() *string {
	if r == nil {
		return nil
	}
	return r.VideoURL
}

func (r *RecordingListResponseRecordingsItem) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *RecordingListResponseRecordingsItem) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetRecordingID sets the RecordingID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RecordingListResponseRecordingsItem) SetRecordingID(recordingID *string) {
	r.RecordingID = recordingID
	r.require(recordingListResponseRecordingsItemFieldRecordingID)
}

// SetLocation sets the Location field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RecordingListResponseRecordingsItem) SetLocation(location *string) {
	r.Location = location
	r.require(recordingListResponseRecordingsItemFieldLocation)
}

// SetStartTime sets the StartTime field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RecordingListResponseRecordingsItem) SetStartTime(startTime *time.Time) {
	r.StartTime = startTime
	r.require(recordingListResponseRecordingsItemFieldStartTime)
}

// SetEndTime sets the EndTime field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RecordingListResponseRecordingsItem) SetEndTime(endTime *time.Time) {
	r.EndTime = endTime
	r.require(recordingListResponseRecordingsItemFieldEndTime)
}

// SetVideoURL sets the VideoURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RecordingListResponseRecordingsItem) SetVideoURL(videoURL *string) {
	r.VideoURL = videoURL
	r.require(recordingListResponseRecordingsItemFieldVideoURL)
}

func (r *RecordingListResponseRecordingsItem) UnmarshalJSON(data []byte) error {
	type embed RecordingListResponseRecordingsItem
	var unmarshaler = struct {
		embed
		StartTime *internal.DateTime `json:"startTime,omitempty"`
		EndTime   *internal.DateTime `json:"endTime,omitempty"`
	}{
		embed: embed(*r),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*r = RecordingListResponseRecordingsItem(unmarshaler.embed)
	r.StartTime = unmarshaler.StartTime.TimePtr()
	r.EndTime = unmarshaler.EndTime.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RecordingListResponseRecordingsItem) MarshalJSON() ([]byte, error) {
	type embed RecordingListResponseRecordingsItem
	var marshaler = struct {
		embed
		StartTime *internal.DateTime `json:"startTime,omitempty"`
		EndTime   *internal.DateTime `json:"endTime,omitempty"`
	}{
		embed:     embed(*r),
		StartTime: internal.NewOptionalDateTime(r.StartTime),
		EndTime:   internal.NewOptionalDateTime(r.EndTime),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RecordingListResponseRecordingsItem) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}
