// Code generated by Fern. DO NOT EDIT.

package roamhq

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersAddReactionRequest(t *testing.T) {
	t.Run("SetChatID", func(t *testing.T) {
		obj := &AddReactionRequest{}
		var fernTestValueChatID string
		obj.SetChatID(fernTestValueChatID)
		assert.Equal(t, fernTestValueChatID, obj.ChatID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTimestamp", func(t *testing.T) {
		obj := &AddReactionRequest{}
		var fernTestValueTimestamp int
		obj.SetTimestamp(fernTestValueTimestamp)
		assert.Equal(t, fernTestValueTimestamp, obj.Timestamp)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetThreadTimestamp", func(t *testing.T) {
		obj := &AddReactionRequest{}
		var fernTestValueThreadTimestamp *int
		obj.SetThreadTimestamp(fernTestValueThreadTimestamp)
		assert.Equal(t, fernTestValueThreadTimestamp, obj.ThreadTimestamp)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetName", func(t *testing.T) {
		obj := &AddReactionRequest{}
		var fernTestValueName string
		obj.SetName(fernTestValueName)
		assert.Equal(t, fernTestValueName, obj.Name)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitAddReactionRequest(t *testing.T) {
	t.Run("SetChatID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AddReactionRequest{}
		var fernTestValueChatID string

		// Act
		obj.SetChatID(fernTestValueChatID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTimestamp_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AddReactionRequest{}
		var fernTestValueTimestamp int

		// Act
		obj.SetTimestamp(fernTestValueTimestamp)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetThreadTimestamp_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AddReactionRequest{}
		var fernTestValueThreadTimestamp *int

		// Act
		obj.SetThreadTimestamp(fernTestValueThreadTimestamp)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AddReactionRequest{}
		var fernTestValueName string

		// Act
		obj.SetName(fernTestValueName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersListReactionRequest(t *testing.T) {
	t.Run("SetChatID", func(t *testing.T) {
		obj := &ListReactionRequest{}
		var fernTestValueChatID string
		obj.SetChatID(fernTestValueChatID)
		assert.Equal(t, fernTestValueChatID, obj.ChatID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTimestamp", func(t *testing.T) {
		obj := &ListReactionRequest{}
		var fernTestValueTimestamp int
		obj.SetTimestamp(fernTestValueTimestamp)
		assert.Equal(t, fernTestValueTimestamp, obj.Timestamp)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetThreadTimestamp", func(t *testing.T) {
		obj := &ListReactionRequest{}
		var fernTestValueThreadTimestamp *int
		obj.SetThreadTimestamp(fernTestValueThreadTimestamp)
		assert.Equal(t, fernTestValueThreadTimestamp, obj.ThreadTimestamp)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitListReactionRequest(t *testing.T) {
	t.Run("SetChatID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListReactionRequest{}
		var fernTestValueChatID string

		// Act
		obj.SetChatID(fernTestValueChatID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTimestamp_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListReactionRequest{}
		var fernTestValueTimestamp int

		// Act
		obj.SetTimestamp(fernTestValueTimestamp)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetThreadTimestamp_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListReactionRequest{}
		var fernTestValueThreadTimestamp *int

		// Act
		obj.SetThreadTimestamp(fernTestValueThreadTimestamp)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersRemoveReactionRequest(t *testing.T) {
	t.Run("SetChatID", func(t *testing.T) {
		obj := &RemoveReactionRequest{}
		var fernTestValueChatID string
		obj.SetChatID(fernTestValueChatID)
		assert.Equal(t, fernTestValueChatID, obj.ChatID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTimestamp", func(t *testing.T) {
		obj := &RemoveReactionRequest{}
		var fernTestValueTimestamp int
		obj.SetTimestamp(fernTestValueTimestamp)
		assert.Equal(t, fernTestValueTimestamp, obj.Timestamp)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetThreadTimestamp", func(t *testing.T) {
		obj := &RemoveReactionRequest{}
		var fernTestValueThreadTimestamp *int
		obj.SetThreadTimestamp(fernTestValueThreadTimestamp)
		assert.Equal(t, fernTestValueThreadTimestamp, obj.ThreadTimestamp)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetName", func(t *testing.T) {
		obj := &RemoveReactionRequest{}
		var fernTestValueName string
		obj.SetName(fernTestValueName)
		assert.Equal(t, fernTestValueName, obj.Name)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitRemoveReactionRequest(t *testing.T) {
	t.Run("SetChatID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RemoveReactionRequest{}
		var fernTestValueChatID string

		// Act
		obj.SetChatID(fernTestValueChatID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTimestamp_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RemoveReactionRequest{}
		var fernTestValueTimestamp int

		// Act
		obj.SetTimestamp(fernTestValueTimestamp)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetThreadTimestamp_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RemoveReactionRequest{}
		var fernTestValueThreadTimestamp *int

		// Act
		obj.SetThreadTimestamp(fernTestValueThreadTimestamp)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RemoveReactionRequest{}
		var fernTestValueName string

		// Act
		obj.SetName(fernTestValueName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersReaction(t *testing.T) {
	t.Run("SetName", func(t *testing.T) {
		obj := &Reaction{}
		var fernTestValueName string
		obj.SetName(fernTestValueName)
		assert.Equal(t, fernTestValueName, obj.Name)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCount", func(t *testing.T) {
		obj := &Reaction{}
		var fernTestValueCount int
		obj.SetCount(fernTestValueCount)
		assert.Equal(t, fernTestValueCount, obj.Count)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetUsers", func(t *testing.T) {
		obj := &Reaction{}
		var fernTestValueUsers []string
		obj.SetUsers(fernTestValueUsers)
		assert.Equal(t, fernTestValueUsers, obj.Users)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersReaction(t *testing.T) {
	t.Run("GetName", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Reaction{}
		var expected string
		obj.Name = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetName(), "getter should return the property value")
	})

	t.Run("GetName_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Reaction
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetName() // Should return zero value
	})

	t.Run("GetCount", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Reaction{}
		var expected int
		obj.Count = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCount(), "getter should return the property value")
	})

	t.Run("GetCount_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Reaction
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCount() // Should return zero value
	})

	t.Run("GetUsers", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Reaction{}
		var expected []string
		obj.Users = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetUsers(), "getter should return the property value")
	})

	t.Run("GetUsers_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Reaction{}
		obj.Users = nil

		// Act & Assert
		assert.Nil(t, obj.GetUsers(), "getter should return nil when property is nil")
	})

	t.Run("GetUsers_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Reaction
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetUsers() // Should return zero value
	})

}

func TestSettersMarkExplicitReaction(t *testing.T) {
	t.Run("SetName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Reaction{}
		var fernTestValueName string

		// Act
		obj.SetName(fernTestValueName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCount_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Reaction{}
		var fernTestValueCount int

		// Act
		obj.SetCount(fernTestValueCount)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetUsers_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Reaction{}
		var fernTestValueUsers []string

		// Act
		obj.SetUsers(fernTestValueUsers)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersListReactionResponse(t *testing.T) {
	t.Run("SetOk", func(t *testing.T) {
		obj := &ListReactionResponse{}
		var fernTestValueOk *bool
		obj.SetOk(fernTestValueOk)
		assert.Equal(t, fernTestValueOk, obj.Ok)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetChatID", func(t *testing.T) {
		obj := &ListReactionResponse{}
		var fernTestValueChatID string
		obj.SetChatID(fernTestValueChatID)
		assert.Equal(t, fernTestValueChatID, obj.ChatID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTimestamp", func(t *testing.T) {
		obj := &ListReactionResponse{}
		var fernTestValueTimestamp int
		obj.SetTimestamp(fernTestValueTimestamp)
		assert.Equal(t, fernTestValueTimestamp, obj.Timestamp)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetThreadTimestamp", func(t *testing.T) {
		obj := &ListReactionResponse{}
		var fernTestValueThreadTimestamp *int
		obj.SetThreadTimestamp(fernTestValueThreadTimestamp)
		assert.Equal(t, fernTestValueThreadTimestamp, obj.ThreadTimestamp)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetReactions", func(t *testing.T) {
		obj := &ListReactionResponse{}
		var fernTestValueReactions []*Reaction
		obj.SetReactions(fernTestValueReactions)
		assert.Equal(t, fernTestValueReactions, obj.Reactions)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPollVotes", func(t *testing.T) {
		obj := &ListReactionResponse{}
		var fernTestValuePollVotes []*ListReactionResponsePollVotesItem
		obj.SetPollVotes(fernTestValuePollVotes)
		assert.Equal(t, fernTestValuePollVotes, obj.PollVotes)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersListReactionResponse(t *testing.T) {
	t.Run("GetOk", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListReactionResponse{}
		var expected *bool
		obj.Ok = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetOk(), "getter should return the property value")
	})

	t.Run("GetOk_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListReactionResponse{}
		obj.Ok = nil

		// Act & Assert
		assert.Nil(t, obj.GetOk(), "getter should return nil when property is nil")
	})

	t.Run("GetOk_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListReactionResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetOk() // Should return zero value
	})

	t.Run("GetChatID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListReactionResponse{}
		var expected string
		obj.ChatID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetChatID(), "getter should return the property value")
	})

	t.Run("GetChatID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListReactionResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetChatID() // Should return zero value
	})

	t.Run("GetTimestamp", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListReactionResponse{}
		var expected int
		obj.Timestamp = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTimestamp(), "getter should return the property value")
	})

	t.Run("GetTimestamp_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListReactionResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTimestamp() // Should return zero value
	})

	t.Run("GetThreadTimestamp", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListReactionResponse{}
		var expected *int
		obj.ThreadTimestamp = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetThreadTimestamp(), "getter should return the property value")
	})

	t.Run("GetThreadTimestamp_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListReactionResponse{}
		obj.ThreadTimestamp = nil

		// Act & Assert
		assert.Nil(t, obj.GetThreadTimestamp(), "getter should return nil when property is nil")
	})

	t.Run("GetThreadTimestamp_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListReactionResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetThreadTimestamp() // Should return zero value
	})

	t.Run("GetReactions", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListReactionResponse{}
		var expected []*Reaction
		obj.Reactions = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetReactions(), "getter should return the property value")
	})

	t.Run("GetReactions_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListReactionResponse{}
		obj.Reactions = nil

		// Act & Assert
		assert.Nil(t, obj.GetReactions(), "getter should return nil when property is nil")
	})

	t.Run("GetReactions_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListReactionResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetReactions() // Should return zero value
	})

	t.Run("GetPollVotes", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListReactionResponse{}
		var expected []*ListReactionResponsePollVotesItem
		obj.PollVotes = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetPollVotes(), "getter should return the property value")
	})

	t.Run("GetPollVotes_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListReactionResponse{}
		obj.PollVotes = nil

		// Act & Assert
		assert.Nil(t, obj.GetPollVotes(), "getter should return nil when property is nil")
	})

	t.Run("GetPollVotes_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListReactionResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetPollVotes() // Should return zero value
	})

}

func TestSettersMarkExplicitListReactionResponse(t *testing.T) {
	t.Run("SetOk_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListReactionResponse{}
		var fernTestValueOk *bool

		// Act
		obj.SetOk(fernTestValueOk)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetChatID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListReactionResponse{}
		var fernTestValueChatID string

		// Act
		obj.SetChatID(fernTestValueChatID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTimestamp_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListReactionResponse{}
		var fernTestValueTimestamp int

		// Act
		obj.SetTimestamp(fernTestValueTimestamp)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetThreadTimestamp_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListReactionResponse{}
		var fernTestValueThreadTimestamp *int

		// Act
		obj.SetThreadTimestamp(fernTestValueThreadTimestamp)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetReactions_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListReactionResponse{}
		var fernTestValueReactions []*Reaction

		// Act
		obj.SetReactions(fernTestValueReactions)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPollVotes_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListReactionResponse{}
		var fernTestValuePollVotes []*ListReactionResponsePollVotesItem

		// Act
		obj.SetPollVotes(fernTestValuePollVotes)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersListReactionResponsePollVotesItem(t *testing.T) {
	t.Run("SetOptionID", func(t *testing.T) {
		obj := &ListReactionResponsePollVotesItem{}
		var fernTestValueOptionID string
		obj.SetOptionID(fernTestValueOptionID)
		assert.Equal(t, fernTestValueOptionID, obj.OptionID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetText", func(t *testing.T) {
		obj := &ListReactionResponsePollVotesItem{}
		var fernTestValueText *string
		obj.SetText(fernTestValueText)
		assert.Equal(t, fernTestValueText, obj.Text)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCount", func(t *testing.T) {
		obj := &ListReactionResponsePollVotesItem{}
		var fernTestValueCount int
		obj.SetCount(fernTestValueCount)
		assert.Equal(t, fernTestValueCount, obj.Count)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetUsers", func(t *testing.T) {
		obj := &ListReactionResponsePollVotesItem{}
		var fernTestValueUsers []string
		obj.SetUsers(fernTestValueUsers)
		assert.Equal(t, fernTestValueUsers, obj.Users)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersListReactionResponsePollVotesItem(t *testing.T) {
	t.Run("GetOptionID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListReactionResponsePollVotesItem{}
		var expected string
		obj.OptionID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetOptionID(), "getter should return the property value")
	})

	t.Run("GetOptionID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListReactionResponsePollVotesItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetOptionID() // Should return zero value
	})

	t.Run("GetText", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListReactionResponsePollVotesItem{}
		var expected *string
		obj.Text = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetText(), "getter should return the property value")
	})

	t.Run("GetText_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListReactionResponsePollVotesItem{}
		obj.Text = nil

		// Act & Assert
		assert.Nil(t, obj.GetText(), "getter should return nil when property is nil")
	})

	t.Run("GetText_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListReactionResponsePollVotesItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetText() // Should return zero value
	})

	t.Run("GetCount", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListReactionResponsePollVotesItem{}
		var expected int
		obj.Count = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCount(), "getter should return the property value")
	})

	t.Run("GetCount_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListReactionResponsePollVotesItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCount() // Should return zero value
	})

	t.Run("GetUsers", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListReactionResponsePollVotesItem{}
		var expected []string
		obj.Users = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetUsers(), "getter should return the property value")
	})

	t.Run("GetUsers_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListReactionResponsePollVotesItem{}
		obj.Users = nil

		// Act & Assert
		assert.Nil(t, obj.GetUsers(), "getter should return nil when property is nil")
	})

	t.Run("GetUsers_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListReactionResponsePollVotesItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetUsers() // Should return zero value
	})

}

func TestSettersMarkExplicitListReactionResponsePollVotesItem(t *testing.T) {
	t.Run("SetOptionID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListReactionResponsePollVotesItem{}
		var fernTestValueOptionID string

		// Act
		obj.SetOptionID(fernTestValueOptionID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetText_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListReactionResponsePollVotesItem{}
		var fernTestValueText *string

		// Act
		obj.SetText(fernTestValueText)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCount_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListReactionResponsePollVotesItem{}
		var fernTestValueCount int

		// Act
		obj.SetCount(fernTestValueCount)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetUsers_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListReactionResponsePollVotesItem{}
		var fernTestValueUsers []string

		// Act
		obj.SetUsers(fernTestValueUsers)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingListReactionResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListReactionResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled ListReactionResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj ListReactionResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj ListReactionResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingListReactionResponsePollVotesItem(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListReactionResponsePollVotesItem{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled ListReactionResponsePollVotesItem
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj ListReactionResponsePollVotesItem
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj ListReactionResponsePollVotesItem
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingReaction(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Reaction{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled Reaction
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj Reaction
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj Reaction
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringListReactionResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &ListReactionResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListReactionResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringListReactionResponsePollVotesItem(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &ListReactionResponsePollVotesItem{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListReactionResponsePollVotesItem
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringReaction(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &Reaction{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Reaction
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestExtraPropertiesListReactionResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &ListReactionResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListReactionResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesListReactionResponsePollVotesItem(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &ListReactionResponsePollVotesItem{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListReactionResponsePollVotesItem
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesReaction(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &Reaction{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Reaction
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
