// Code generated by Fern. DO NOT EDIT.

package userauditlog

import (
	context "context"

	roamhq "ro.am/roamhq"
	core "ro.am/roamhq/core"
	internal "ro.am/roamhq/internal"
	option "ro.am/roamhq/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Get a list of user audit log entries for the account.
//
// **Required scope:** `userauditlog:read`
//
// Example:
//
//	request := &roamhq.ListUserAuditLogRequest{}
//	client.UserAuditLog.List(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) List(
	ctx context.Context,
	request *roamhq.ListUserAuditLogRequest,
	opts ...option.RequestOption,
) (*roamhq.ListUserAuditLogResponse, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
