// Code generated by Fern. DO NOT EDIT.

package groups

import (
	context "context"

	roamhq "ro.am/roamhq"
	core "ro.am/roamhq/core"
	internal "ro.am/roamhq/internal"
	option "ro.am/roamhq/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// **Legacy:** Prefer [`/group.list`](https://developer.ro.am/docs/api/group-list) for new integrations.
//
// Lists all public, non-archived groups in your home Roam.
//
// Unlike `/group.list`, this endpoint returns a **raw JSON array** (not the
// `{"ok": true, …}` envelope). It is the sole ok-envelope exception on `/v1`
// and remains only for existing callers.
//
// **Access:** Organization only.
//
// **Required scope:** `group:read`
//
// Example:
//
//	client.Groups.List(
//	    context.TODO(),
//	)
func (c *Client) List(
	ctx context.Context,
	opts ...option.RequestOption,
) ([]*roamhq.GroupsListResponseItem, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
