// Code generated by Fern. DO NOT EDIT.

package chat_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	require "github.com/stretchr/testify/require"
	roamhq "ro.am/roamhq"
	client "ro.am/roamhq/client"
	option "ro.am/roamhq/option"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestChatListWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &roamhq.ListChatRequest{}
	_, invocationErr := client.Chat.List(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestChatListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestChatListWithWireMock", "GET", "/chat.list", nil, 1)
}

func TestChatPostWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &roamhq.PostChatRequest{
		ChatID: roamhq.String(
			"757dfe66-37b4-4772-baa5-8c86ec68c176",
		),
		Text: roamhq.String(
			"Hello from the **API**",
		),
	}
	_, invocationErr := client.Chat.Post(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestChatPostWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestChatPostWithWireMock", "POST", "/chat.post", nil, 1)
}

func TestChatPostEphemeralWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &roamhq.PostEphemeralChatRequest{
		ChatID: "295155ae-7df5-4ed5-9ebc-89a170559c81",
		UserID: "7861a4c6-765a-495d-898d-fae3d8fbba2d",
		Text:   "Only *you* can see this: your deploy token expires in 3 days.",
	}
	_, invocationErr := client.Chat.PostEphemeral(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestChatPostEphemeralWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestChatPostEphemeralWithWireMock", "POST", "/chat.postEphemeral", nil, 1)
}

func TestChatListScheduledWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &roamhq.ListScheduledChatRequest{}
	_, invocationErr := client.Chat.ListScheduled(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestChatListScheduledWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestChatListScheduledWithWireMock", "GET", "/chat.scheduled.list", nil, 1)
}

func TestChatCancelScheduledWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &roamhq.CancelScheduledChatRequest{
		ScheduledMessageID: "0197f9f0-5cc1-7d07-8a12-9e65a8a0c1b9",
	}
	_, invocationErr := client.Chat.CancelScheduled(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestChatCancelScheduledWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestChatCancelScheduledWithWireMock", "POST", "/chat.scheduled.cancel", nil, 1)
}

func TestChatStartStreamWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &roamhq.StartStreamChatRequest{
		GroupID: roamhq.String(
			"88bebce7-6cbb-4666-96f9-5c02d73e6661",
		),
		Text: roamhq.String(
			"Let me look into that...",
		),
	}
	_, invocationErr := client.Chat.StartStream(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestChatStartStreamWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestChatStartStreamWithWireMock", "POST", "/chat.startStream", nil, 1)
}

func TestChatAppendStreamWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &roamhq.AppendStreamChatRequest{
		StreamID: "018f5c8e-7d2a-7c4e-8f9a-1a2b3c4d5e6f",
		Text:     " The answer is 42.",
	}
	_, invocationErr := client.Chat.AppendStream(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestChatAppendStreamWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestChatAppendStreamWithWireMock", "POST", "/chat.appendStream", nil, 1)
}

func TestChatStopStreamWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &roamhq.StopStreamChatRequest{
		StreamID: "018f5c8e-7d2a-7c4e-8f9a-1a2b3c4d5e6f",
		Text: roamhq.String(
			" Hope that helps!",
		),
	}
	_, invocationErr := client.Chat.StopStream(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestChatStopStreamWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestChatStopStreamWithWireMock", "POST", "/chat.stopStream", nil, 1)
}

func TestChatUpdateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &roamhq.UpdateChatRequest{
		ChatID:    "757dfe66-37b4-4772-baa5-8c86ec68c176",
		Timestamp: 1765602474760032,
		Text: roamhq.String(
			"Updated message content with **bold text**",
		),
	}
	_, invocationErr := client.Chat.Update(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestChatUpdateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestChatUpdateWithWireMock", "POST", "/chat.update", nil, 1)
}

func TestChatDeleteWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &roamhq.DeleteChatRequest{
		ChatID:    "757dfe66-37b4-4772-baa5-8c86ec68c176",
		Timestamp: 1765602474760032,
	}
	_, invocationErr := client.Chat.Delete(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestChatDeleteWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestChatDeleteWithWireMock", "POST", "/chat.delete", nil, 1)
}

func TestChatTypingWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &roamhq.TypingChatRequest{
		ChatID: roamhq.String(
			"295155ae-7df5-4ed5-9ebc-89a170559c81",
		),
	}
	invocationErr := client.Chat.Typing(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestChatTypingWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestChatTypingWithWireMock", "POST", "/chat.typing", nil, 1)
}

func TestChatHistoryWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &roamhq.HistoryChatRequest{}
	_, invocationErr := client.Chat.History(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestChatHistoryWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestChatHistoryWithWireMock", "GET", "/chat.history", nil, 1)
}

func TestChatSearchWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &roamhq.SearchChatRequest{
		After: roamhq.String(
			"2026-04-13",
		),
		Limit: roamhq.Int(
			20,
		),
	}
	_, invocationErr := client.Chat.Search(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestChatSearchWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestChatSearchWithWireMock", "POST", "/chat.search", nil, 1)
}

func TestChatResolveLinkWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &roamhq.ResolveLinkChatRequest{
		Link: "https://ro.am/r/#/d/abc123xyz/c/757dfe66-37b4-4772-baa5-8c86ec68c176?ts=1765602474760032",
	}
	_, invocationErr := client.Chat.ResolveLink(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestChatResolveLinkWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestChatResolveLinkWithWireMock", "POST", "/chat.link.resolve", nil, 1)
}

func TestChatCreateLinkWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &roamhq.CreateLinkChatRequest{
		ChatID: roamhq.String(
			"295155ae-7df5-4ed5-9ebc-89a170559c81",
		),
		Timestamp: int64(1765602474760032),
	}
	_, invocationErr := client.Chat.CreateLink(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestChatCreateLinkWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestChatCreateLinkWithWireMock", "POST", "/chat.link.create", nil, 1)
}

func TestChatUnfurlWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &roamhq.UnfurlChatRequest{
		ChatID:           "8f3b9c2e-1a4d-4e7b-9c0a-2b6d1f5e3a7c",
		MessageTimestamp: 1748906400000000,
		Unfurls: map[string]*roamhq.UnfurlContent{
			"https://status.example.com/incidents/123": &roamhq.UnfurlContent{
				Title: "Incident 123",
				Description: roamhq.String(
					"Investigating elevated errors",
				),
				SiteName: roamhq.String(
					"PagerDuty",
				),
				Favicon: roamhq.String(
					"https://status.example.com/favicon.png",
				),
				Image: &roamhq.UnfurlContentImage{
					URL: "https://status.example.com/incident.png",
					Type: roamhq.String(
						"image/png",
					),
					Width: roamhq.Int(
						1200,
					),
					Height: roamhq.Int(
						630,
					),
					Alt: roamhq.String(
						"Incident status",
					),
				},
			},
		},
	}
	_, invocationErr := client.Chat.Unfurl(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestChatUnfurlWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestChatUnfurlWithWireMock", "POST", "/chat.unfurl", nil, 1)
}
