// Code generated by Fern. DO NOT EDIT.

package group

import (
	context "context"
	http "net/http"

	roamhq "ro.am/roamhq"
	core "ro.am/roamhq/core"
	internal "ro.am/roamhq/internal"
	option "ro.am/roamhq/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Lists non-archived groups accessible to the caller.
//
// Filter by name with `query` (ranked text match), restrict by group
// type with `type`, and paginate with `limit` / `cursor`.
//
// **Access:** Organization and Personal.
//
// **Required scope:** `group:read`
//
// Example:
//
//	request := &roamhq.ListGroupRequest{}
//	client.Group.List(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) List(
	ctx context.Context,
	request *roamhq.ListGroupRequest,
	opts ...option.RequestOption,
) (*core.Page[*string, *roamhq.ListGroupResponseGroupsItem, *roamhq.ListGroupResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"https://api.ro.am/v1",
	)
	endpointURL := baseURL + "/group.list"
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	headers := internal.MergeHeaders(
		c.options.ToHeader(),
		options.ToHeader(),
	)
	prepareCall := func(pageRequest *core.PageRequest[*string]) *internal.CallParams {
		if pageRequest.Cursor != nil {
			queryParams.Set("cursor", *pageRequest.Cursor)
		}
		nextURL := endpointURL
		if len(queryParams) > 0 {
			nextURL += "?" + queryParams.Encode()
		}
		return &internal.CallParams{
			URL:             nextURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        pageRequest.Response,
			ErrorDecoder:    internal.NewErrorDecoder(roamhq.ErrorCodes),
		}
	}
	readPageResponse := func(response *roamhq.ListGroupResponse) *core.PageResponse[*string, *roamhq.ListGroupResponseGroupsItem, *roamhq.ListGroupResponse] {
		var zeroValue *string
		next := response.GetNextCursor()
		results := response.GetGroups()
		return &core.PageResponse[*string, *roamhq.ListGroupResponseGroupsItem, *roamhq.ListGroupResponse]{
			Results:  results,
			Response: response,
			Next:     next,
			Done:     next == zeroValue || *next == "",
		}
	}
	pager := internal.NewCursorPager(
		c.caller,
		prepareCall,
		readPageResponse,
	)
	return pager.GetPage(ctx, request.Cursor)
}

// Get information about a specific group by its ID or name.
//
// Provide either `id` or `name`, not both.
//
// **Required scope:** `group:read`
//
// Example:
//
//	request := &roamhq.InfoGroupRequest{}
//	client.Group.Info(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Info(
	ctx context.Context,
	request *roamhq.InfoGroupRequest,
	opts ...option.RequestOption,
) (*roamhq.Group, error) {
	response, err := c.WithRawResponse.Info(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Create a group chat.
//
// Groups which specify at least one admin will operate in an "Admin only" management
// mode, where only admins may change settings. Otherwise, all members have
// that capability.
//
// Groups require at least one member. Users can be specified by user ID or email address.
//
// **Required scope:** `group:write`
//
// Example:
//
//	request := &roamhq.CreateGroupRequest{
//	    Name: "Engineering Team",
//	    Description: roamhq.String(
//	        "Group chat for engineering discussions and updates",
//	    ),
//	    Private: roamhq.Bool(
//	        false,
//	    ),
//	    EnforceThreads: roamhq.Bool(
//	        true,
//	    ),
//	    Members: []*roamhq.CreateGroupRequestMembersItem{
//	        &roamhq.CreateGroupRequestMembersItem{
//	            UserID: "alex.chen@example.com",
//	            Role: roamhq.CreateGroupRequestMembersItemRoleMember,
//	        },
//	        &roamhq.CreateGroupRequestMembersItem{
//	            UserID: "taylor@example.com",
//	            Role: roamhq.CreateGroupRequestMembersItemRoleMember,
//	        },
//	        &roamhq.CreateGroupRequestMembersItem{
//	            UserID: "jordan.smith@example.com",
//	            Role: roamhq.CreateGroupRequestMembersItemRoleAdmin,
//	        },
//	    },
//	}
//	client.Group.Create(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Create(
	ctx context.Context,
	request *roamhq.CreateGroupRequest,
	opts ...option.RequestOption,
) (*roamhq.Group, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Rename a group by ID.
//
// Apps may only rename groups for which they are an admin.
//
// **Required scope:** `group:write`
//
// Example:
//
//	request := &roamhq.RenameGroupRequest{
//	    ID: "88bebce7-6cbb-4666-96f9-5c02d73e6661",
//	    Name: "Product Engineering",
//	}
//	client.Group.Rename(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Rename(
	ctx context.Context,
	request *roamhq.RenameGroupRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.Rename(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// Archive a group by ID.
//
// Apps may only archive groups for which they are an admin.
//
// **Required scope:** `group:write`
//
// Example:
//
//	request := &roamhq.ArchiveGroupRequest{
//	    ID: "88bebce7-6cbb-4666-96f9-5c02d73e6661",
//	}
//	client.Group.Archive(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Archive(
	ctx context.Context,
	request *roamhq.ArchiveGroupRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.Archive(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// List members in a group with their roles.
//
// Apps may list members if one of the following conditions is true:
// 1. It is a public group in their Roam.
// 2. They are a member of the group.
//
// **Required scope:** `group:read`
//
// Every returned `userId` is a visible principal ID that resolves through
// [`user.info`](https://developer.ro.am/docs/api/user-info) with the same credentials. Use
// `user.list?ids` for ordered bulk hydration.
//
// Example:
//
//	request := &roamhq.MembersGroupRequest{
//	    ID: "id",
//	}
//	client.Group.Members(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Members(
	ctx context.Context,
	request *roamhq.MembersGroupRequest,
	opts ...option.RequestOption,
) (*core.Page[*string, *roamhq.GroupMember, *roamhq.MembersGroupResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"https://api.ro.am/v1",
	)
	endpointURL := baseURL + "/group.members"
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	headers := internal.MergeHeaders(
		c.options.ToHeader(),
		options.ToHeader(),
	)
	prepareCall := func(pageRequest *core.PageRequest[*string]) *internal.CallParams {
		if pageRequest.Cursor != nil {
			queryParams.Set("cursor", *pageRequest.Cursor)
		}
		nextURL := endpointURL
		if len(queryParams) > 0 {
			nextURL += "?" + queryParams.Encode()
		}
		return &internal.CallParams{
			URL:             nextURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        pageRequest.Response,
			ErrorDecoder:    internal.NewErrorDecoder(roamhq.ErrorCodes),
		}
	}
	readPageResponse := func(response *roamhq.MembersGroupResponse) *core.PageResponse[*string, *roamhq.GroupMember, *roamhq.MembersGroupResponse] {
		var zeroValue *string
		next := response.GetNextCursor()
		results := response.GetMembers()
		return &core.PageResponse[*string, *roamhq.GroupMember, *roamhq.MembersGroupResponse]{
			Results:  results,
			Response: response,
			Next:     next,
			Done:     next == zeroValue || *next == "",
		}
	}
	pager := internal.NewCursorPager(
		c.caller,
		prepareCall,
		readPageResponse,
	)
	return pager.GetPage(ctx, request.Cursor)
}

// Add one or more group members with specified roles.
//
// Members can be specified by user ID or email address. Each member must be assigned a role (member or admin).
//
// Apps may add members to a group if one of the following conditions is true:
// 1. It is a public group in their Roam.
// 2. They are a member of the group.
//
// If attempting to add an admin, the app must be an admin of the group.
//
// **Required scope:** `group:write`
//
// Example:
//
//	request := &roamhq.AddGroupRequest{
//	    ID: "88bebce7-6cbb-4666-96f9-5c02d73e6661",
//	    Members: []*roamhq.AddGroupRequestMembersItem{
//	        &roamhq.AddGroupRequestMembersItem{
//	            UserID: "709b8a57-70bc-427a-b6f0-b16ba5297f8c",
//	            Role: roamhq.AddGroupRequestMembersItemRoleMember,
//	        },
//	        &roamhq.AddGroupRequestMembersItem{
//	            UserID: "f589a8cb-78ac-493e-8719-0fa8a22f65e0",
//	            Role: roamhq.AddGroupRequestMembersItemRoleMember,
//	        },
//	        &roamhq.AddGroupRequestMembersItem{
//	            UserID: "af6663d5-0f37-4105-95df-4fea20ef7c7c",
//	            Role: roamhq.AddGroupRequestMembersItemRoleAdmin,
//	        },
//	    },
//	}
//	client.Group.Add(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Add(
	ctx context.Context,
	request *roamhq.AddGroupRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.Add(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// Join a public group as the calling identity (Slack `conversations.join`).
//
//   - Org tokens add the bot address as a member.
//   - Personal tokens add the **owner person**, never the PAT bot address.
//   - Private groups cannot be self-joined (`403`).
//   - Idempotent if the calling identity is already a member.
//   - Non-members of a group in another roam receive an opaque `403`
//     (`group_not_found`) — archived / type / privacy are not distinguished.
//
// Why join (webhooks vs history vs post): [Chat](https://developer.ro.am/docs/guides/chat).
//
// **Access:** Organization and Personal.
//
// **Required scope:** `group:write`
//
// Example:
//
//	request := &roamhq.JoinGroupRequest{
//	    ID: "88bebce7-6cbb-4666-96f9-5c02d73e6661",
//	}
//	client.Group.Join(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Join(
	ctx context.Context,
	request *roamhq.JoinGroupRequest,
	opts ...option.RequestOption,
) (*roamhq.Group, error) {
	response, err := c.WithRawResponse.Join(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Remove one or more group members.
//
// Members can be specified by user ID or email address.
//
// Apps may remove members from a group if one of the following conditions is true:
// 1. It is a public group in their Roam.
// 2. They are a member of the group.
//
// Removing members with the Admin role is not yet supported.
//
// **Required scope:** `group:write`
//
// Example:
//
//	request := &roamhq.RemoveGroupRequest{
//	    ID: "88bebce7-6cbb-4666-96f9-5c02d73e6661",
//	    Members: []string{
//	        "709b8a57-70bc-427a-b6f0-b16ba5297f8c",
//	    },
//	}
//	client.Group.Remove(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Remove(
	ctx context.Context,
	request *roamhq.RemoveGroupRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.Remove(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}
